// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.HRSystemStatusControl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // SystemSequenceControl
    public class SystemSequenceControlConfiguration : IEntityTypeConfiguration<SystemSequenceControl>
    {
        public void Configure(EntityTypeBuilder<SystemSequenceControl> builder)
        {
            builder.ToTable("SystemSequenceControl", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SystemSequence").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.SystemControlDateId).HasColumnName(@"SystemControlDateId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired(false).IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            builder.HasOne(a => a.SystemControlDate).WithMany(b => b.SystemSequenceControls).HasForeignKey(c => c.SystemControlDateId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SystemSequenceControl_SystemControlDate");
        }
    }

}
// </auto-generated>
