// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.HRSystemStatusControl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // SystemControlDate
    public class SystemControlDateConfiguration : IEntityTypeConfiguration<SystemControlDate>
    {
        public void Configure(EntityTypeBuilder<SystemControlDate> builder)
        {
            builder.ToTable("SystemControlDate", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SystemSequenceControl_1").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EntryExitReferDate).HasColumnName(@"EntryExitReferDate").HasColumnType("int").IsRequired();
            builder.Property(x => x.MonthlyPayReferDate).HasColumnName(@"MonthlyPayReferDate").HasColumnType("int").IsRequired();
            builder.Property(x => x.PersonnelReferDate).HasColumnName(@"PersonnelReferDate").HasColumnType("int").IsRequired();
            builder.Property(x => x.AttendAbsenceItemDate).HasColumnName(@"AttendAbsenceItemDate").HasColumnType("int").IsRequired();
            builder.Property(x => x.BonusCalculateDate).HasColumnName(@"BonusCalculateDate").HasColumnType("int").IsRequired();
            builder.Property(x => x.SalaryDate).HasColumnName(@"SalaryDate").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired(false).IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();
        }
    }

}
// </auto-generated>
