using Ksc.HR.Data.Persistant.Configurations;
using Ksc.HR.Domain.Entities;
using Ksc.HR.Domain.Entities.ODSViews;
using Ksc.HR.Domain.Entities.Workshift;
using Ksc.HR.Domain.Entities.WorkFlow;
using Ksc.HR.Domain.Entities.Oncall;
using Microsoft.EntityFrameworkCore;
using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Transfer;
using Ksc.HR.Domain.Entities.HRSystemStatusControl;
using Ksc.HR.Data.Persistant.Configurations.Dismissal;
using Ksc.HR.Domain.Entities.Dismissal;
using Microsoft.Data.SqlClient;
using Ksc.HR.Data.Persistant.Configurations.Emp;
using Ksc.HR.Domain.Entities.Emp;

using Ksc.HR.Data.Persistant.Configurations.ODSViews;
using Ksc.HR.Domain.Entities.ScheduledLoger;
using Ksc.Hr.Domain.Entities.Personal;
using Ksc.Hr.Data.Persistant.Configurations.Personal;
using Ksc.HR.Data.Persistant.Configurations.Personal;
using Ksc.Hr.Domain.Entities;
using Ksc.Hr.Data.Persistant.Configurations;
using Ksc.HR.Domain.Entities.BusinessTrip;
using Ksc.HR.Data.Persistant.Configurations.BusinessTrip;
using KSC.Infrastructure.Persistance;
using System.Data.Common;
using KSC.Domain;
using Ksc.HR.Domain.Entities.Chart;
using Ksc.HR.Data.Persistant.Configurations.Chart;
using Ksc.HR.Data.Persistant.Configurations.Stepper;
using Ksc.HR.Domain.Entities.Stepper;
using sc.HR.Data.Persistant.Configurations.Stepper;
using Ksc.HR.Domain.Entities.EmployeeBase;
using Ksc.HR.Data.Persistant.Configurations.EmployeeBase;
using sc.HR.Data.Persistant.Configurations.EmployeeBase;
using Ksc.HR.Domain.Entities.Emp;
using Ksc.Hr.Data.Persistant.Configurations.Emp;
using Ksc.HR.Domain.Entities.Log;
using Ksc.HR.Data.Persistant.Configurations.Log;
using sc.HR.Data.Persistant.Configurations.Log;
using Ksc.HR.Domain.Entities.Pay;
using Ksc.HR.Domain.Entities.Salary;
using Ksc.Hr.Data.Persistant.Configurations.Pay;
using System.Reflection;
using Ksc.HR.Domain.Entities.Rule;
using Ksc.HR.Domain.Entities.Reward;
using Ksc.HR.Domain.Entities.Defines;
using Ksc.HR.Domain.Entities.StandBy;

using Ksc.Hr.Domain.Repositories;
using Ksc.HR.Domain.Entities.Security;
using Ksc.HR.Domain.Entities.View;
#nullable disable

namespace Ksc.HR.Data.Persistant.Context
{
    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


    public partial class KscHrContext : DbContext
    {
        public KscHrContext()
        {
        }

        public KscHrContext(DbContextOptions<KscHrContext> options)
            : base(options)
        {

        }

        
        public DbSet<V_JobPosition> V_JobPosition { get; set; }
        public DbSet<View_Employee> View_Employees { get; set; }
        public DbSet<ViewShiftBoard> ViewShiftBoard { get; set; }
        public DbSet<View_PresentEmployees> View_PresentEmployees { get; set; }

        public DbSet<LicenseType> LicenseTypes { get; set; }
        public DbSet<LicenseJobPosition> LicenseJobPositions { get; set; }
        public DbSet<Relocation> Relocations { get; set; }
        public DbSet<RelocationType> RelocationTypes { get; set; }
        public DbSet<RelocationStatus> RelocationStatuses { get; set; }
        public DbSet<JobCategoryDefinitionGuide> JobCategoryDefinitionGuides { get; set; }

        //public DbSet<TEntity> Set<TEntity>() where TEntity : class => base.Set<TEntity>();
        public DbSet<EventListener> EventListener { get; set; }

        // ViewShiftBoard
        public DbSet<EmployeeSafetyDeduction> EmployeeSafetyDeductions { get; set; } // EmployeeSafetyDeduction
        public virtual DbSet<EmployeePromotionInterdicts> EmployeePromotionInterdicts { get; set; }
        public DbSet<ViewOdsTherapyBookletMis> ViewOdsTherapyBookletMis { get; set; } // ViewOdsTherapyBookletMis
        public DbSet<ViewOdsJobStatusCategory> ViewOdsJobStatusCategories { get; set; } // View_ODS_JobStatusCategory
        public DbSet<ViewOdsJobPositionTree> ViewOdsJobPositionTrees { get; set; } // ViewOdsJobPositionTree
        public DbSet<EmployeeEducationTime> EmployeeEducationTimes { get; set; } // EmployeeEducationTime
        public DbSet<AccessLevel> AccessLevels { get; set; } // AccessLevel
        public DbSet<CalendarEvent> CalendarEvents { get; set; } // CalendarEvent
        public DbSet<City> Cities { get; set; } // City
        public DbSet<Company> Companies { get; set; } // Company
        public DbSet<CompatibleRollCall> CompatibleRollCalls { get; set; } // CompatibleRollCall
        public DbSet<Country> Countries { get; set; } // Country
        public DbSet<DayNightSettingTime> DayNightSettingTimes { get; set; } // DayNightSettingTime
        public DbSet<EntryExitType> EntryExitTypes { get; set; } // EntryExitType
        public DbSet<IncludedDefinition> IncludedDefinitions { get; set; } // IncludedDefinition
        public DbSet<IncludedRollCall> IncludedRollCalls { get; set; } // IncludedRollCall
        public DbSet<OverTimeDefinition> OverTimeDefinitions { get; set; } // OverTimeDefinition
        public DbSet<Province> Provinces { get; set; } // Province
        public DbSet<RollCallCategory> RollCallCategories { get; set; } // RollCallCategory
        public DbSet<RollCallConcept> RollCallConcepts { get; set; } // RollCallConcept
        public DbSet<RollCallDefinition> RollCallDefinitions { get; set; } // RollCallDefinition
        public DbSet<RollCallJobCategory> RollCallJobCategories { get; set; } // RollCallJobCategory
        public DbSet<RollCallSalaryCode> RollCallSalaryCodes { get; set; } // RollCallSalaryCode
        public DbSet<ShiftBoard> ShiftBoards { get; set; } // ShiftBoard
        public DbSet<ShiftConcept> ShiftConcepts { get; set; } // ShiftConcept
        public DbSet<ShiftConceptDetail> ShiftConceptDetails { get; set; } // ShiftConceptDetail
        public DbSet<ShiftHoliday> ShiftHolidays { get; set; } // ShiftHoliday
        public DbSet<TeamWork> TeamWorks { get; set; } // TeamWork
        public DbSet<TeamWorkCategory> TeamWorkCategories { get; set; } // TeamWorkCategory
        public DbSet<TeamWorkCategoryType> TeamWorkCategoryTypes { get; set; } // TeamWorkCategoryType
        public DbSet<TeamWorkMangementCode> TeamWorkMangementCodes { get; set; } // TeamWorkMangementCode
        public DbSet<TimeSheetStatus> TimeSheetStatus { get; set; } // TimeSheetStatus
        public DbSet<TimeShiftSetting> TimeShiftSettings { get; set; } // TimeShiftSetting
        public DbSet<ViewMisCostCenter> ViewMisCostCenters { get; set; } // View_MIS_CostCenter
        public DbSet<ViewMisEmploymentType> ViewMisEmploymentType { get; set; } // View_Mis_EmploymentType
        public DbSet<ViewMisJobCategory> ViewMisJobCategories { get; set; } // View_MIS_JobCategory
        public DbSet<ViewMisSalaryCode> ViewMisSalaryCodes { get; set; } // View_MIS_SalaryCode
        public DbSet<WorkCalendar> WorkCalendars { get; set; } // WorkCalendar
        public DbSet<WorkCity> WorkCities { get; set; } // WorkCity

        public DbSet<WorkCompanySetting> WorkCompanySettings { get; set; } // WorkCompanySetting
        public DbSet<WorkDayTimeSetting> WorkDayTimeSettings { get; set; } // WorkDayTimeSetting
        public DbSet<WorkDayType> WorkDayTypes { get; set; } // WorkDayType
        public DbSet<WorkGroup> WorkGroups { get; set; } // WorkGroup
        public DbSet<WorkTime> WorkTimes { get; set; } // WorkTime
        public DbSet<WorkTimeCategory> WorkTimeCategories { get; set; } // WorkTimeCategory

        public DbSet<WF_AccessManagement> WF_AccessManagements { get; set; } // WF_AccessManagement
        public DbSet<WF_JobCategoryRange> WF_JobCategoryRanges { get; set; } // WF_JobCategoryRange
        public DbSet<WF_Priority> WF_Priorities { get; set; } // WF_Priority
        public DbSet<WF_Process> WF_Processes { get; set; } // WF_Priority
        public DbSet<WF_Request> WF_Requests { get; set; } // WF_Priority
        public DbSet<WF_RequestHistory> WF_RequestHistories { get; set; } // WF_Priority
        public DbSet<WF_Role> WF_Roles { get; set; } // WF_Priority
        public DbSet<WF_Status> WF_Statuses { get; set; } // WF_Priority
        public DbSet<WF_StatusProcessManagement> WF_StatusProcessManagements { get; set; } // WF_Priority
        public DbSet<WF_StatusReason> WF_StatusReasons { get; set; } // WF_Priority
        public DbSet<WF_ValidJobCategory> WF_ValidJobCategories { get; set; } // WF_Priority
        public DbSet<WF_WorkFlowManagement> WF_WorkFlowManagements { get; set; } // WF_Priority
        public DbSet<WF_WorkFlowStatusReason> WF_WorkFlowStatusReasons { get; set; } // WF_Priority

        public DbSet<OnCall_Request> OnCall_Requests { get; set; } // OnCall_Request
        public DbSet<OnCall_Type> OnCall_Types { get; set; } //OnCall_Type
        public DbSet<OnCall_WorkTime> OnCall_WorkTimes { get; set; } //OnCall_WorkTime


        public DbSet<Employee> Employees { get; set; } //Employee
        public DbSet<EmployeeAttendAbsenceItem> EmployeeAttendAbsenceItems { get; set; } // EmployeeAttendAbsenceItem
        public DbSet<EmployeeEntryExit> EmployeeEntryExits { get; set; } // EmployeeEntryExit
        public DbSet<EmployeeBreastfedding> EmployeeBreastfedding { get; set; } // EmployeeBreastfedding
        public DbSet<EmployeeWorkGroup> EmployeeWorkGroups { get; set; } // EmployeeLongTermAbsence
        public DbSet<EmployeeLongTermAbsence> EmployeeLongTermAbsences { get; set; } // EmployeeLongTermAbsence
        public DbSet<ViewMisUserDefinition> ViewMisUserDefinition { get; set; } //View_MIS_UserDefinition

        public DbSet<ViewMisSubFunction> ViewMisSubFunctions { get; set; } //ViewMisSubFunction
        public DbSet<OnCall_AcessManagmentOnCallType> OnCall_AcessManagmentOnCallType { get; set; } //OnCall_AcessManagmentOnCallType
        public DbSet<ViewMisJobPosition> ViewMisJobPosition { get; set; } // ViewMisJobPosition
        public DbSet<ViewMisEmployee> ViewMisEmployee { get; set; } // ViewMisEmployee


        public DbSet<Transfer_Request> Transfer_Requests { get; set; } // Request
        public DbSet<Transfer_RequestReason> Transfer_RequestReasons { get; set; } // RequestReason
        public DbSet<Transfer_RequestReasonType> Transfer_RequestReasonTypes { get; set; } // RequestReasonType
        public DbSet<Transfer_RequestType> Transfer_RequestTypes { get; set; } // RequestType
        public DbSet<Transfer_Type> Transfer_Types { get; set; } // Type
        public DbSet<Transfer_RequestReasonJobCategory> Transfer_RequestReasonJobCategories { get; set; } // RequestReasonJobCategory
        public DbSet<EmployeeTeamWork> EmployeeTeamWorks { get; set; } // EmployeeTeamWork

        public DbSet<ViewMisEmployeeSecurity> ViewMisEmployeeSecurities { get; set; } // View_MIS_EmployeeSecurity
        public DbSet<SystemControlDate> SystemControlDates { get; set; } // SystemControlDate
        public DbSet<SystemSequenceControl> SystemSequenceControls { get; set; } // SystemSequenceControl
        public DbSet<SystemSequenceStatus> SystemSequenceStatus { get; set; } // SystemSequenceStatus
        public DbSet<RollCallEmploymentType> RollCallEmploymentTypes { get; set; } // RollCallEmploymentType

        public DbSet<UnofficialHolidayReason> UnofficialHolidayReasons { get; set; } // UnofficialHolidayReason
        public DbSet<WorkCompanyUnOfficialHolidayJobCategory> WorkCompanyUnOfficialHolidayJobCategories { get; set; } // WorkCompanyUnOfficialHolidayJobCategory
        public DbSet<WorkCompanyUnOfficialHolidaySetting> WorkCompanyUnOfficialHolidaySettings { get; set; } // WorkCompanyUnOfficialHolidaySetting
        public DbSet<WorkTimeShiftConcept> WorkTimeShiftConcepts { get; set; } // WorkTimeShiftConcept
        public DbSet<TimeSheetSetting> TimeSheetSettings { get; set; } // TimeSheetSetting
        public DbSet<EmployeeEntryExitAttendAbsence> EmployeeEntryExitAttendAbsences { get; set; } // EmployeeEntryExitAttendAbsence
        public DbSet<SacrificeOptionSetting> SacrificeOptionSettings { get; set; } // SacrificeOptionSetting
        public DbSet<SacrificePercentageSetting> SacrificePercentageSettings { get; set; } // SacrificePercentageSetting
        public DbSet<Dismissal_Request> Dismissal_Request { get; set; } // SacrificePercentageSetting
        public DbSet<SpEmployeeTeamNotConfirmedReturnModel> SpEmployeeTeamNotConfirmedReturnModels { get; set; }
        public DbSet<SpGetEmployeeLeaveStatusReturnModel> SpGetEmployeeLeaveStatusReturnModels { get; set; }
        public DbSet<TrainingType> TrainingTypes { get; set; } // TrainingType
        public DbSet<Dismissal_Status> Dismissal_Status { get; set; } // Status
        public DbSet<PaymentStatus> PaymentStatus { get; set; } // PaymentStatus
        public DbSet<AnalysisEmployeeAttendAbsenceItem> AnalysisEmployeeAttendAbsenceItems { get; set; } // AnalysisEmployeeAttendAbsenceItem
        public DbSet<ScheduledLog> ScheduledLogs { get; set; } //ScheduledLog
        public DbSet<OfficialMessage> OfficialMessages { get; set; } // AnalysisEmployeeAttendAbsenceItem
        public DbSet<RollCallWorkTimeDayType> RollCallWorkTimeDayTypes { get; set; } // RollCallWorkTimeDayType
        public DbSet<DayNightPercentEmplymentType> DayNightPercentEmplymentTypes { get; set; } // DayNightPercentEmplymentType
        public DbSet<DayNightRollCall> DayNightRollCalls { get; set; } // DayNightRollCall
        public DbSet<MonthTimeSheet> MonthTimeSheets { get; set; } // MonthTimeSheet
        public DbSet<MonthTimeSheetDraft> MonthTimeSheetDrafts { get; set; } // MonthTimeSheetDraft
        public DbSet<MonthTimeSheetIncluded> MonthTimeSheetIncludeds { get; set; } // MonthTimeSheetIncluded
        public DbSet<MonthTimeSheetRollCall> MonthTimeSheetRollCalls { get; set; } // MonthTimeSheetRollCall
        public DbSet<MonthTimeSheetWorkTime> MonthTimeSheetWorkTimes { get; set; } // MonthTimeSheetWorkTime
        public DbSet<MonthTimeSheetLog> MonthTimeSheetLogs { get; set; } // MonthTimeSheetLog

        public DbSet<ViewTimeSheetToMis> ViewTimeSheetToMiss { get; set; } // MonthTimeSheetWorkTime
        public DbSet<OverTimeSpecialHolidayTimeSheetSetting> OverTimeSpecialHolidayTimeSheetSettings { get; set; } // OverTimeSpecialHolidayTimeSheetSetting
        public DbSet<EmployeeTimeSheet> EmployeeTimeSheets { get; set; } // EmployeeTimeSheet
        public DbSet<ViewTeamManager> ViewTeamManagers { get; set; } // View_TeamManager
        public DbSet<MonthTimeShitStepper> MonthTimeShitSteppers { get; set; } // MonthTimeShitStepper
        public DbSet<ViewAttendItemReport> ViewAttendItemReport { get; set; } // MonthTimeShitStepper
        public DbSet<ViewEmployeeTeamUserActive> ViewEmployeeTeamUserActive { get; set; } // ViewEmployeeTeamUserActive
        public DbSet<Mission_Location> Mission_Locations { get; set; } // Location
        public DbSet<Mission_Goal> Mission_Goals { get; set; } // Goal
        public DbSet<Mission_Request> Mission_Requests { get; set; } // Request
        public DbSet<Mission_Type> Mission_Types { get; set; } // Type
        public DbSet<Mission_TypeAccessLevel> Mission_TypeAccessLevels { get; set; } // TypeAccessLevel

        public DbSet<DayTimeSetting> DayTimeSettings { get; set; } // DayTimeSetting
        public DbSet<MaritalStatus> MaritalStatus { get; set; } // MaritalStatus
        public DbSet<FloatTimeSetting> FloatTimeSettings { get; set; } // FloatTimeSetting
        public DbSet<EmployeeEfficiencyHistory> EmployeeEfficiencyHistory { get; set; } // EmployeeEfficiencyHistory
        public DbSet<EmployeeEfficiencyMonth> EmployeeEfficiencyMonth { get; set; } // EmployeeEfficiencyMonth
        public DbSet<ViewNotConfirmedEducation> ViewNotConfirmedEducation { get; set; } // EmployeeEfficiencyHistory

        public DbSet<Chart_JobCategory> Chart_JobCategory { get; set; }
        public DbSet<Chart_JobCategoryDefination> Chart_JobCategoryDefination { get; set; }
        public DbSet<Chart_JobCategoryEducation> Chart_JobCategoryEducation { get; set; }
        public DbSet<Chart_JobIdentity> Chart_JobIdentity { get; set; }
        public DbSet<Chart_JobPosition> Chart_JobPosition { get; set; }
        public DbSet<Chart_JobPositionField> Chart_JobPositionField { get; set; }
        public DbSet<Chart_JobPositionHistory> Chart_JobPositionHistory { get; set; }
        public DbSet<Chart_JobPositionIncreasePercent> Chart_JobPositionIncreasePercent { get; set; }
        public DbSet<Chart_JobPositionScore> Chart_JobPositionScore { get; set; }
        public DbSet<Chart_JobPositionScoreType> Chart_JobPositionScoreType { get; set; }
        public DbSet<Chart_JobCertificate> Chart_JobCertificate { get; set; }
        public DbSet<Chart_JobPositionCertificate> Chart_JobPositionCertificate { get; set; }
        public DbSet<JobGroup> JobGroup { get; set; }



        public DbSet<Chart_JobPositionStatus> Chart_JobPositionStatus { get; set; }
        public DbSet<Chart_JobPositionStatusCategory> Chart_JobPositionStatusCategory { get; set; }
        public DbSet<Chart_RewardSpecific> Chart_RewardSpecific { get; set; }
        public DbSet<Chart_Structure> Chart_Structure { get; set; }
        public DbSet<Chart_StructureAccess> Chart_StructureAccess { get; set; }
        public DbSet<Chart_StructureType> Chart_StructureType { get; set; }
        public DbSet<Chart_StructureTypeQuickAccess> Chart_StructureTypeQuickAccess { get; set; }
        public DbSet<Education> Education { get; set; }
        public DbSet<ViewJobPosition> viewJobPositions { get; set; } // TypeLocation
        public DbSet<StudyField> StudyField { get; set; }
        public DbSet<Chart_JobPositionNature> Chart_JobPositionNature { get; set; }
        public DbSet<WF_WorkFlowAction> WF_WorkFlowActions { get; set; } // WorkFlowAction
        public DbSet<Mission_TypeLocation> Mission_TypeLocations { get; set; } // TypeLocation
        public DbSet<Stepper_Procedure> Stepper_Procedures { get; set; } // Procedure
        public DbSet<Stepper_ProcedureLog> Stepper_ProcedureLogs { get; set; } // ProcedureLog
        public DbSet<Stepper_ProcedureStatus> Stepper_ProcedureStatus { get; set; } // ProcedureStatus
        public DbSet<Stepper_ProcedureAccessLevel> Stepper_ProcedureAccessLevels { get; set; } // Stepper_ProcedureAccessLevel
        public DbSet<Stepper_StatusSystemMonth> Stepper_StatusSystemMonths { get; set; } // Stepper_StatusSystemMonth

        public DbSet<InsuranceType> InsuranceTypes { get; set; } // InsuranceType
        public DbSet<InsuranceList> InsuranceLists { get; set; } // InsuranceType
        public DbSet<BloodType> BloodType { get; set; }
        public DbSet<IsarStatus> IsarStatus { get; set; }
        public DbSet<Nationality> Nationality { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<GenderType> GenderType { get; set; }
        public DbSet<MilitaryDegree> MilitaryDegrees { get; set; } // MilitaryDegrees
        public DbSet<MilitaryType> MilitaryTypes { get; set; } // MilitaryType
        public DbSet<MilitaryUnit> MilitaryUnits { get; set; } // MilitaryUnits
        public DbSet<MilitaryStatus> MilitaryStatues { get; set; } // MilitaryStatus
        public DbSet<MilitaryExemptionReason> MilitaryExemptionReasons { get; set; } // MilitaryExemptionReasons
        public DbSet<AccountBankType> AccountBankTypes { get; set; } // AccountBankType
        public DbSet<EmployeePaymentStatus> EmployeePaymentStatues { get; set; } // EmployeePaymentStatus
        public DbSet<EmployeeOtherPaymentTemplate> EmployeeOtherPaymentTemplates { get; set; } // EmployeePaymentStatus
        public DbSet<EmployeePicture> EmployeePictures { get; set; } // EmployeePaymentStatus
        public DbSet<EmployeeVacationManagementLog> EmployeeVacationManagementLogs { get; set; } // EmployeePaymentStatus

        

        public DbSet<DependenceJob> DependenceJob { get; set; } // DependenceJob
        public DbSet<DependenceReason> DependenceReason { get; set; } // DependenceReason
        public DbSet<DependenceType> DependenceType { get; set; } // DependenceType
        public DbSet<DependentExitDateReason> DependentExitDateReason { get; set; } // DependentExitDateReason

        public DbSet<Family> Family { get; set; } // Family
        public DbSet<EmployeeValidOverTime> EmployeeValidOverTime { get; set; } // EmployeeValidOverTime



        public DbSet<EmploymentType> EmploymentTypes { get; set; } // EmploymentType
        public DbSet<EmploymentStatus> EmploymentStatuses { get; set; } // EmploymentStatuses
        public DbSet<EmployeeEducationDegree> EmployeeEducationDegrees { get; set; } // EmployeeEducationDegree

        public DbSet<SavingType> SavingTypes { get; set; } // SavingTypes

        public DbSet<EmployeeJobPosition> EmployeeJobPositions { get; set; }
        public DbSet<EmployeeAccountBank> EmployeeAccountBanks { get; set; }



        public DbSet<TableDefinition> TableDefinitions { get; set; }

        public DbSet<InsuranceBooklet> InsuranceBooklet { get; set; }
        public DbSet<FranchiseType> FranchiseType { get; set; }

        //
        public DbSet<EntityType> EntityTypes { get; set; } // EntityTypes
        public DbSet<OperationType> OperationTypes { get; set; } // OperationTypes
        public DbSet<LogData> LogDatas { get; set; } // LogDatas

        public DbSet<PaymentStatusAccess> PaymentStatusAccesses { get; set; } // PaymentStatusAccess

        public DbSet<BookletEmployeeWithFamilyAndBank> BookletEmployeeWithFamilyAndBanks { get; set; } // LogDatas
        public DbSet<ViewGeneralDataEmployeeWithFamily> View_GeneralDataEmployeeWithFamilies { get; set; } // LogDatas
        public DbSet<ViewGeneralDataEmployeeWithFamilyForReport> View_GeneralDataEmployeeWithFamiliesForReport { get; set; } // LogDatas

        public DbSet<ViewEmployeeFamilyReport> viewEmployeeFamilyReports { get; set; }
        public DbSet<HrOption> HrOptions { get; set; }
        public DbSet<PersonalType> PersonalType { get; set; }

        public DbSet<OtherPaymentSetting> OtherPaymentSetting { get; set; }
        public DbSet<OtherPaymentStatus> OtherPaymentStatus { get; set; }
        public DbSet<OtherPaymentStatusFlow> OtherPaymentStatusFlow { get; set; }
        public DbSet<OtherPaymentType> OtherPaymentType { get; set; }
        public DbSet<EmployeeOtherPayment> EmployeeOtherPayment { get; set; }
        public DbSet<EmployeeOtherPaymentHistory> EmployeeOtherPaymentHistory { get; set; }
        public DbSet<EmployeeOtherPaymentType> EmployeeOtherPaymentType { get; set; }
        public DbSet<EmployeeBlackList> EmployeeBlackList { get; set; }
        //
        public DbSet<EmployeeConditionalAbsence> EmployeeConditionalAbsences { get; set; }
        public DbSet<ConditionalAbsenceSubject> ConditionalAbsenceSubjects { get; set; }
        public DbSet<ConditionalAbsenceSubjectType> ConditionalAbsenceSubjectTypes { get; set; } // ConditionalAbsenceSubjectType
        public DbSet<ConditionalAbsenceType> ConditionalAbsenceTypes { get; set; }

        //


        public DbSet<OtherPaymentDetail> OtherPaymentDetail { get; set; }
        public DbSet<OtherPaymentHeader> OtherPaymentHeader { get; set; }
        public DbSet<AccountCode> AccountCode { get; set; }
        public DbSet<OtherPaymentSettingParameter> OtherPaymentSettingParameters { get; set; } // OtherPaymentSettingParameter
        public DbSet<OtherPaymentSettingParameterValue> OtherPaymentSettingParameterValues { get; set; } // OtherPaymentSettingParameterValue
        public DbSet<KUnitSetting> KUnitSettings { get; set; } // KUnitSetting
        public DbSet<OtherPaymentHeaderType> OtherPaymentHeaderTypes { get; set; } // OtherPaymentHeaderType
        public DbSet<OtherPaymentPercentage> OtherPaymentPercentages { get; set; } // OtherPaymentPercentage
        public DbSet<EmployeeVacationHistory> EmployeeVacationHistories { get; set; }
        public DbSet<RewardType> RewardTypes { get; set; }
        public DbSet<RewardLevel> RewardLevels { get; set; }
        public DbSet<StudentRewardSetting> StudentRewardSettings { get; set; }
        public DbSet<StudentRewardRequest> StudentRewardRequests { get; set; }

        public DbSet<ViewOnCallRequest> ViewOnCallRequests { get; set; } // View_OnCallRequest
        public DbSet<ViewEmployeeWithFamilyActive> ViewEmployeeWithFamilyActives { get; set; } // ViewEmployeeWithFamilyActives
        public DbSet<ViewMisEmployeeDiscipline> ViewMisEmployeeDiscipline { get; set; } // ViewMisEmployeeDiscipline

        public DbSet<Mission_TypeLocationWorkCity> Mission_TypeLocationWorkCities { get; set; } // TypeLocationWorkCity
        public DbSet<ViewOdsEmployeeWithChartData> ViewOdsEmployeeWithChartDatas { get; set; } // View_Ods_EmployeeWithChartData
        public virtual DbSet<Vacation> Vacation { get; set; }
        public virtual DbSet<EmployeeVacationManagement> EmployeeVacationManagements { get; set; }

        public DbSet<EmployeeVacationSold> EmployeeVacationSolds { get; set; } // EmployeeVacationSold
        //Role
        public DbSet<ReasonJobMoving> ReasonJobMovings { get; set; } // ReasonJobMoving
        public DbSet<InterdictType> InterdictTypes { get; set; } // InterdictType
        public DbSet<InterdictCategory> InterdictCategory { get; set; } // InterdictType
        public DbSet<PaymentType> PaymentType { get; set; } // InterdictType
        public DbSet<InterdictStatus> InterdictStatus { get; set; } // InterdictStatus
        public DbSet<InterdictDescription> InterdictDescription { get; set; } // InterdictDescription
        public DbSet<EmployeeInterdict> EmployeeInterdicts { get; set; } // EmployeeInterdict
        public DbSet<EmployeeInterdictDetail> EmployeeInterdictDetails { get; set; } // EmployeeInterdictDetails
        public DbSet<SignatureImage> SignatureImages { get; set; } // SignatureImages

        public DbSet<InterdictMaritalSetting> InterdictMaritalSetting { get; set; } // InterdictMaritalSetting
        public DbSet<InterdictMaritalSettingDetail> InterdictMaritalSettingDetails { get; set; } // InterdictMaritalSettingDetails
        //reward
        public DbSet<RewardBaseDetail> RewardBaseDetails { get; set; } // InterdictMaritalSettingDetails
        public DbSet<RewardBaseHeader> RewardBaseHeaders { get; set; } // InterdictMaritalSettingDetails
        public DbSet<RewardIn> RewardIns { get; set; } // RewardIns
        public DbSet<RewardInDailyProductionSale> RewardInDailyProductionSales { get; set; } // RewardInDailyProductionSales
        public DbSet<RewardInMonthlyProductionSale> RewardInMonthlyProductionSales { get; set; } // RewardInMonthlyProductionSales
        public DbSet<RewardInQualityControlMonthlyDri> RewardInQualityControlMonthlyDris { get; set; } // RewardInQualityControlMonthlyDris
        public DbSet<RewardInQualityControlMonthlyPelet> RewardInQualityControlMonthlyPelets { get; set; } // RewardInQualityControlMonthlyPelets
        public DbSet<RewardInQualityControlMonthlyProduction> RewardInQualityControlMonthlyProductions { get; set; } // RewardInQualityControlMonthlyProductions
        public DbSet<RewardInSmcDailyProduction> RewardInSmcDailyProductions { get; set; } // RewardInSmcDailyProductions
        public DbSet<RewardInSmcMonthlyProduction> RewardInSmcMonthlyProductions { get; set; } // RewardInSmcMonthlyProductions
        public DbSet<RewardOutDetail> RewardOutDetails { get; set; } // RewardOutDetails
        public DbSet<RewardOutHeader> RewardOutHeaders { get; set; } // RewardOutHeaders
        public DbSet<RewardCategory> RewardCategorys { get; set; } // RewardCategorys
        public DbSet<RewardUnitType> RewardUnitTypes { get; set; } // RewardUnitTypes
        public DbSet<CountingUnit> CountingUnits { get; set; } // CountingUnits
        public DbSet<ProductionEfficiency> ProductionEfficiencys { get; set; } // ProductionEfficiencys

        public DbSet<RewardBaseSpecific> RewardBaseSpecifics { get; set; } // RewardBaseSpecific
        public DbSet<RewardBaseSpecificOfUnitDetail> RewardBaseSpecificOfUnitDetails { get; set; } // RewardBaseSpecificOfUnitDetails
        public DbSet<RewardBaseSpecificOfUnitHeader> RewardBaseSpecificOfUnitHeaders { get; set; } // RewardBaseSpecificOfUnitHeaders


        public DbSet<AccountPaymentTypeSetting> AccountPaymentTypeSettings { get; set; } // SignatureImages
        public DbSet<BasisSalaryItem> BasisSalaryItems { get; set; } // SignatureImages
        public DbSet<BasisSalaryItemPerGroup> BasisSalaryItemPerGroups { get; set; } // SignatureImages
        public DbSet<Coefficient> Coefficient { get; set; } // SignatureImages
        public DbSet<CoefficientSetting> CoefficientSetting { get; set; } // SignatureImages
        public DbSet<AccountEmploymentType> AccountEmploymentType { get; set; } // SignatureImages
        public DbSet<AccountCodeMarital> AccountCodeMarital { get; set; } // SignatureImages
        public DbSet<HrFormulas> HrFormulas { get; set; }
        public DbSet<PropertyAccountType> PropertyAccountTypes { get; set; }
        public DbSet<AccountCodeCompatibleType> AccountCodeCompatibleTypes { get; set; }
        public DbSet<PropertyAccount> PropertyAccounts { get; set; }
        public DbSet<AccountCodeCategory> AccountCodeCategories { get; set; }
        public DbSet<PropertyAccountSetting> PropertyAccountSettings { get; set; }
        public DbSet<PaymentAccountCode> PaymentAccountCodes { get; set; }
        public DbSet<AccountCodeCompatible> AccountCodeCompatibles { get; set; }
        public DbSet<EmployeeHaveTravel> EmployeeHaveTravels { get; set; }
        public DbSet<ReasonJobMoving> ReasonJobMoving { get; set; }
        public DbSet<ProductionEfficiency> ProductionEfficiencies { get; set; }
        public DbSet<CategoryCoefficient> categoryCoefficients { get; set; }
        public DbSet<InterdictWeather> InterdictWeather { get; set; }
        public DbSet<MeritRating> MeritRatings { get; set; }
        public DbSet<EmployeePercentMeritHistory> EmployeePercentMeritHistories { get; set; }
        public DbSet<HistoryTypeEmployement> HistoryTypeEmployements { get; set; }
        public DbSet<EmployeeHistoryTypeEmployement> EmployeeHistoryTypeEmployements { get; set; }
        public DbSet<DisConnectionType> DisConnectionTypes { get; set; }
        public DbSet<EmployeeDisConnection> EmployeeDisConnections { get; set; }
        public DbSet<EmployeePromotion> EmployeePromotions { get; set; }
        public DbSet<PromotionRejectReason> PromotionRejectReasons { get; set; }
        public DbSet<PromotionStatus> PromotionStatuses { get; set; }
        public DbSet<EmployeeDateInformation> EmployeeDateInformation { get; set; }
        public DbSet<EducationCategory> EducationCategory { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; } // PaymentDetail
        public DbSet<PaymentHeader> PaymentHeaders { get; set; } // PaymentHeader
        public DbSet<PaymentProcess> PaymentProcesses { get; set; } // PaymentProcess
        public DbSet<PaymentProcessCategory> PaymentProcessCategories { get; set; } // PaymentProcessCategory
        public DbSet<EmployeeReward> EmployeeRewards { get; set; } // EmployeeRewards
        public DbSet<View_MIS_Employee_Home> View_MIS_Employee_Homes { get; set; } // PaymentProcessCategory
        public DbSet<ViewFamilyForOtherPaymentMariedAndBirthDay> ViewFamilyForOtherPaymentMariedAndBirthDay { get; set; } // ViewFamilyForOtherPaymentMariedAndBirthDay
        public DbSet<View_EmployeeForOtherPaymentMariedAndBirthDay> ViewEmployeeForOtherPaymentMariedAndBirthDay { get; set; } // ViewEmployeeForOtherPaymentMariedAndBirthDay
         //Pay       
        public DbSet<DeductionAdditional> DeductionAdditionals { get; set; }
        public DbSet<EmployeeDeductionAdditional> EmployeeDeductionAdditionals { get; set; }
        public DbSet<EmployeeDeductionHeader> EmployeeDeductionHeader { get; set; }
        public DbSet<EmployeeDeductionHeader> EmployeeDeductionTemp { get; set; }
        public DbSet<EmployeeDeductionInstallmentPutOff> EmployeeDeductionInstallmentPutOff { get; set; }
        public DbSet<EmployeeDeductionDetail> EmployeeDeductionDetail { get; set; }
        public DbSet<EmployeeDeductionType> EmployeeDeductionType { get; set; }
        public DbSet<EmployeeDeductionTypeAccess> EmployeeDeductionTypeAccess { get; set; }
        public DbSet<EmployeeDeductionStatus> EmployeeDeductionStatus { get; set; }
        public DbSet<EmployeeLoanDeductionHeader> EmployeeLoanDeductionHeader { get; set; }
        public DbSet<EmployeeLoanDeductionDetail> EmployeeLoanDeductionDetail { get; set; }
        //
        public DbSet<BudgetRewardHeader> BudgetRewardHeader { get; set; }
        public DbSet<BudgetRewardDetail> BudgetRewardDetail { get; set; }
        public DbSet<BudgetRewardEmployee> BudgetRewardEmployee { get; set; }
        public DbSet<BudgetRewardEmployeeHistory> BudgetRewardEmployeeHistories { get; set; }
        public DbSet<BudgetRewardStatus> BudgetRewardStatus { get; set; }
        public DbSet<BudgetRewardType> BudgetRewardType { get; set; }

        
        public DbSet<StandbyEmloyeeBoard> StandbyEmloyeeBoard { get; set; }
        public DbSet<StandbyEmloyeeBoardLog> StandbyEmloyeeBoardLog { get; set; }
        public DbSet<StandbyEmployeeRole> StandbyEmployeeRole { get; set; }
        public DbSet<StandbyHeader> StandbyHeader { get; set; }
        public DbSet<StandbyRole> StandbyRole { get; set; }
        public DbSet<StandbyTurn> StandbyTurn { get; set; }
        public DbSet<StandbyReplacementRequests> StandbyReplacementRequests { get; set; }
        //
        public DbSet<PaymentAdditionalDetail> PaymentAdditionalDetails { get; set; }
        public DbSet<PaymentAdditionalHeader> PaymentAdditionalHeaders { get; set; }
        public DbSet<PaymentAdditionalSetting> PaymentAdditionalSettings { get; set; }
        public DbSet<PaymentAdditionalSettingJobCategory> PaymentAdditionalSettingJobCategories { get; set; }
        public DbSet<PaymentAdditionalSettingWorkCity> PaymentAdditionalSettingWorkCities { get; set; }

        public DbSet<IncreaseSalaryHeader> IncreaseSalaryHeaders { get; set; }
        public DbSet<IncreaseSalaryDetail> IncreaseSalaryDetails { get; set; }
     
        public DbSet<PaymentAdditionalSettingJobPosition> PaymentAdditionalSettingJobPosition { get; set; }
        public DbSet<ConfirmInterdict> ConfirmInterdict { get; set; }
        public DbSet<ConfirmInterdictStatus> ConfirmInterdictStatus { get; set; }
        public DbSet<ConfirmInterdictMessage> ConfirmInterdictMessage { get; set; }

        //security'
        public DbSet<UserDefinition> UserDefinitions { get; set; }
        public DbSet<UserDefinitionSecurityPriorityStatus> UserDefinitionSecurityPriorityStatus { get; set; }
        public DbSet<UserDefinitionSecurityTeamWork> UserDefinitionSecurityTeamWorks { get; set; }
        public DbSet<Chart_JobPositionTeamWork> JobPositionTeamWorks { get; set; }

        public DbSet<Chart_JobPositionNatureSubGroup> JobPositionNatureSubGroups { get; set; }

        public DbSet<CofficientProximityProduct> CofficientProximityProducts { get; set; }
        public DbSet<RollCallWorkTimeMonthSetting> RollCallWorkTimeMonthSettings { get; set; } // RollCallWorkTimeMonthSetting
        public DbSet<InvalidDayTypeInForcedOvertime> InvalidDayTypeInForcedOvertimes { get; set; } // InvalidDayTypeInForcedOvertime
        public DbSet<RollCallWorkCity> RollCallWorkCities { get; set; } // RollCallWorkCity
        public DbSet<AccountCodeDeductionType> AccountCodeDeductionTypes { get; set; } // AccountCodeDeductionType

        public DbSet<EmployeeDeductionActivateStatus> EmployeeDeductionActivateStatus { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
            OnModelCreatingPartial(modelBuilder);

        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    }

    public partial class KscHrContextDbTranctions : KSC.Infrastructure.Persistance.DbTransaction, IDbTransaction
    {
        public KscHrContextDbTranctions(KscHrContext context) : base(context)
        {
        }


    }

}
