// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Stepper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations.Stepper
{
    // ProcedureLog
    public class Stepper_ProcedureLogConfiguration : IEntityTypeConfiguration<Stepper_ProcedureLog>
    {
        public void Configure(EntityTypeBuilder<Stepper_ProcedureLog> builder)
        {
            builder.ToTable("ProcedureLog", "Stepper");
            builder.HasKey(x => x.Id).HasName("PK_ProcedureLog").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ProcedureId).HasColumnName(@"ProcedureId").HasColumnType("int").IsRequired();
            builder.Property(x => x.YearMonth).HasColumnName(@"YearMonth").HasColumnType("int").IsRequired();
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertAuthenticateUserName).HasColumnName(@"InsertAuthenticateUserName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateAuthenticateUserName).HasColumnName(@"UpdateAuthenticateUserName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Stepper_Procedure).WithMany(b => b.Stepper_ProcedureLogs).HasForeignKey(c => c.ProcedureId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ProcedureLog_Procedure");
        }
    }

}
// </auto-generated>
