// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;

namespace Ksc.HR.DTO.WorkShift.WorkCalendar
{
    /// <summary>
    /// تقویم کاری
    /// </summary>
    public  class WorkCalendarViewModel
    {
        public int Id { get; set; } // Id (Primary key)
        public int DateKey { get; set; } // DateKey
        public int DayOfYear { get; set; } // DayOfYear
        public int DayOfWeek { get; set; } // DayOfWeek
        public int WeekOfYear { get; set; } // WeekOfYear
        public int Month { get; set; } // Month
        public int YearMonthV1 { get; set; } // YearMonthV1
        public string YearMonthV2 { get; set; } // YearMonthV2 (length: 7)
        public string SeasonName { get; set; } // SeasonName (length: 50)
        public int SeasonNumber { get; set; } // SeasonNumber
        public string HalfYearName { get; set; } // HalfYearName (length: 50)
        public int HalfYearNumber { get; set; } // HalfYearNumber
        public string ShamsiDateV1 { get; set; } // ShamsiDateV1 (length: 10)
        public string ShamsiDateV2 { get; set; } // ShamsiDateV2
        public DateTime MiladiDateV1 { get; set; } // MiladiDateV1
        public string MiladiDateV2 { get; set; } // MiladiDateV2
        public string HijriDateV1 { get; set; } // HijriDateV1 (length: 10)
        public string HijriDateV2 { get; set; } // HijriDateV2
        public string DayNameShamsi { get; set; } // DayNameShamsi
        public string DayNameMiladi { get; set; } // DayNameMiladi
        public string DayNameHijri { get; set; } // DayNameHijri
        public string MonthNameShamsiV1 { get; set; } // MonthNameShamsiV1
        public string MonthNameMiladiV1 { get; set; } // MonthNameMiladiV1
        public string MonthNameMiladiV2 { get; set; } // MonthNameMiladiV2
        public string MonthNameHijriV1 { get; set; } // MonthNameHijriV1
        public int DayOfMonthShamsi { get; set; } // DayOfMonthShamsi
        public int DayOfMonthHijri { get; set; } // DayOfMonthHijri
        public int DayOfMonthMiladi { get; set; } // DayOfMonthMiladi
        public string MmddShamsi { get; set; } // MMDDShamsi (length: 50)
        public string MmddMiladi { get; set; } // MMDDMiladi (length: 50)
        public string MmddHijri { get; set; } // MMDDHijri (length: 50)
        public int YyyymmShamsi { get; set; } // YYYYMMShamsi
        public int YyyymmMiladi { get; set; } // YYYYMMMiladi
        public int YyyymmHijri { get; set; } // YYYYMMHijri
        public int YyyyShamsi { get; set; } // YYYYShamsi
        public int YyyyHijri { get; set; } // YYYYHijri
        public int YyyyMiladi { get; set; } // YYYYMiladi
    
    }
}