// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Ksc.HR.Data.Persistant.Configurations
{
    // CalendarEvent
    public class CalendarEventConfiguration : IEntityTypeConfiguration<CalendarEvent>
    {
        public void Configure(EntityTypeBuilder<CalendarEvent> builder)
        {
            builder.ToTable("CalendarEvent", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_CalendarEvent").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.CalendarType).HasColumnName(@"CalendarType").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.Mmdd).HasColumnName(@"MMDD").HasColumnType("nvarchar(4)").IsRequired().HasMaxLength(4);
            builder.Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.IsHoliday).HasColumnName(@"IsHoliday").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsHappiness).HasColumnName(@"IsHappiness").HasColumnType("bit").IsRequired(false);
        }
    }
}
