// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // DayNightRollCall
    public class DayNightRollCallConfiguration : IEntityTypeConfiguration<DayNightRollCall>
    {
        public void Configure(EntityTypeBuilder<DayNightRollCall> builder)
        {
            builder.ToTable("DayNightRollCall", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_DayNightRollCall").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.DayNightSettingTimeId).HasColumnName(@"DayNightSettingTimeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.DayNumber).HasColumnName(@"DayNumber").HasColumnType("int").IsRequired();
            builder.Property(x => x.RollCallDefinitionId).HasColumnName(@"RollCallDefinitionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.PercentAmount).HasColumnName(@"PercentAmount").HasColumnType("float").HasPrecision(53).IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.DayNightSettingTime).WithMany(b => b.DayNightRollCalls).HasForeignKey(c => c.DayNightSettingTimeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DayNightRollCall_DayNightSettingTime");
            builder.HasOne(a => a.RollCallDefinition).WithMany(b => b.DayNightRollCalls).HasForeignKey(c => c.RollCallDefinitionId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_DayNightRollCall_RollCallDefinition");
        }
    }

}
// </auto-generated>
