// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // SacrificeOptionSetting
    public class SacrificeOptionSettingConfiguration : IEntityTypeConfiguration<SacrificeOptionSetting>
    {
        public void Configure(EntityTypeBuilder<SacrificeOptionSetting> builder)
        {
            builder.ToTable("SacrificeOptionSetting", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SacrificeOptionSetting").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar(5)").IsRequired().HasMaxLength(5);
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(500)").IsRequired().HasMaxLength(500);
        }
    }

}
// </auto-generated>
