// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ksc.HR.Data.Persistant.Configurations
{
    public partial class ShiftBoardConfiguration : IEntityTypeConfiguration<ShiftBoard>
    {
        public void Configure(EntityTypeBuilder<ShiftBoard> entity)
        {
            entity.ToTable("ShiftBoard", "dbo");
            entity.HasKey(x => x.Id).IsClustered();
            entity.HasComment("لوحه شیفت");

            entity.Property(e => e.DomainName).HasMaxLength(50);

            entity.Property(e => e.InsertDate).HasColumnType("datetime");

            entity.Property(e => e.InsertUser).HasMaxLength(50);

            entity.Property(e => e.IsPeriodStartDate).HasComment("شروع دوره است ؟");

            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.Property(e => e.UpdateUser).HasMaxLength(50);

            entity.HasOne(d => d.ShiftConceptDetail)
                .WithMany(p => p.ShiftBoards)
                .HasForeignKey(d => d.ShiftConceptDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShiftBoard_ShiftConceptDetail");

            entity.HasOne(d => d.WorkCalendar)
                .WithMany(p => p.ShiftBoards)
                .HasForeignKey(d => d.WorkCalendarId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShiftBoard_WorkCalendar");

            entity.HasOne(d => d.WorkGroup)
                .WithMany(p => p.ShiftBoards)
                .HasForeignKey(d => d.WorkGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShiftBoard_WorkGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ShiftBoard> entity);
    }
}
