// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Ksc.HR.Data.Persistant.Configurations
{
    public partial class WorkDayTimeSettingConfiguration : IEntityTypeConfiguration<WorkDayTimeSetting>
    {
        public void Configure(EntityTypeBuilder<WorkDayTimeSetting> entity)
        {
            entity.ToTable("WorkDayTimeSetting", "dbo");
            entity.HasKey(x => x.Id).IsClustered();
            entity.HasComment("تنظیمات شیفت با نوع روز کاری");

            entity.Property(e => e.DomainName).HasMaxLength(50);

            entity.Property(e => e.ExtraWorkPercentageInDay).HasComment("درصد اضافه کار در روز");

            entity.Property(e => e.ExtraWorkPercentageInNight).HasComment("درصد اضافه کار در شب");

            entity.Property(e => e.InsertDate).HasColumnType("datetime");

            entity.Property(e => e.InsertUser).HasMaxLength(50);

            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.Property(e => e.UpdateUser).HasMaxLength(50);

            entity.HasOne(d => d.WorkDayType)
                .WithMany(p => p.WorkDayTimeSettings)
                .HasForeignKey(d => d.WorkDayTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkDayTimeSetting_WorkDayType");

            entity.HasOne(d => d.WorkTime)
                .WithMany(p => p.WorkDayTimeSettings)
                .HasForeignKey(d => d.WorkTimeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkDayShiftSetting_WorkTime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkDayTimeSetting> entity);
    }
}
