// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // WorkTimeShiftConcept
    public class WorkTimeShiftConceptConfiguration : IEntityTypeConfiguration<WorkTimeShiftConcept>
    {
        public void Configure(EntityTypeBuilder<WorkTimeShiftConcept> builder)
        {
            builder.ToTable("WorkTimeShiftConcept", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_WorkTimeShiftConcept").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.WorkTimeId).HasColumnName(@"WorkTimeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ShiftConceptId).HasColumnName(@"ShiftConceptId").HasColumnType("int").IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            builder.HasOne(a => a.ShiftConcept).WithMany(b => b.WorkTimeShiftConcepts).HasForeignKey(c => c.ShiftConceptId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_WorkTimeShiftConcept_ShiftConcept");
            builder.HasOne(a => a.WorkTime).WithMany(b => b.WorkTimeShiftConcepts).HasForeignKey(c => c.WorkTimeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_WorkTimeShiftConcept_WorkTime");
        }
    }

}
// </auto-generated>
