// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Reward;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // RewardInQualityControlMonthlyDri
    public class RewardInQualityControlMonthlyDriConfiguration : IEntityTypeConfiguration<RewardInQualityControlMonthlyDri>
    {
        public void Configure(EntityTypeBuilder<RewardInQualityControlMonthlyDri> builder)
        {
            builder.ToTable("RewardInQualityControlMonthlyDri", "Reward");
            builder.HasKey(x => x.Id).HasName("PK_RewardInQualityControlMonthlyDri").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RewardInId).HasColumnName(@"RewardInId").HasColumnType("int").IsRequired();
            builder.Property(x => x.PlantName).HasColumnName(@"PlantName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.QualityPercent).HasColumnName(@"QualityPercent").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.MetalPercent).HasColumnName(@"MetalPercent").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.Spare3).HasColumnName(@"Spare3").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.CSuggestionFactorDri).HasColumnName(@"CSuggestionFactorDri").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.ProductionEfficiencyId).HasColumnName(@"ProductionEfficiencyId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.RewardIn).WithMany(b => b.RewardInQualityControlMonthlyDris).HasForeignKey(c => c.RewardInId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_RewardInQualityControlMonthlyDri_RewardIn");
        }
    }

}
// </auto-generated>
