// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.HRSystemStatusControl
{
    // SystemSequenceControl
    public class SystemSequenceControl : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int SystemControlDateId { get; set; } // SystemControlDateId
        public string Title { get; set; } // Title (length: 100)
        public int? Code { get; set; } // Code
        public string Name { get; set; } // Name (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child SystemSequenceStatus where [SystemSequenceStatus].[SystemSequenceControlId] point to this entity (FK_SystemSequenceStatus_SystemSequenceControl)
        /// </summary>
        public virtual ICollection<SystemSequenceStatus> SystemSequenceStatus { get; set; } // SystemSequenceStatus.FK_SystemSequenceStatus_SystemSequenceControl

        // Foreign keys

        /// <summary>
        /// Parent SystemControlDate pointed by [SystemSequenceControl].([SystemControlDateId]) (FK_SystemSequenceControl_SystemControlDate)
        /// </summary>
        public virtual SystemControlDate SystemControlDate { get; set; } // FK_SystemSequenceControl_SystemControlDate

        public SystemSequenceControl()
        {
            SystemSequenceStatus = new List<SystemSequenceStatus>();
        }
    }

}
// </auto-generated>
