// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Security

{
    // UserDefinitionSecurityPriorityStatus
    /// <summary>
    /// جدول اولویت دسترسی
    /// </summary>
    public class UserDefinitionSecurityPriorityStatus : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 200)

        /// <summary>
        /// تاریخ ایجاد
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر ایجاد کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ بروزرسانی
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر بروزرسانی کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child Security_UserDefinitionSecurityTeamWorks where [UserDefinitionSecurityTeamWork].[UserDefinitionSecurityPriorityStatusId] point to this entity (FK_UserDefinitionSecurityTeamWork_UserDefinitionSecurityPriorityStatus)
        /// </summary>
        public virtual ICollection<UserDefinitionSecurityTeamWork> UserDefinitionSecurityTeamWorks { get; set; } // UserDefinitionSecurityTeamWork.FK_UserDefinitionSecurityTeamWork_UserDefinitionSecurityPriorityStatus

        public UserDefinitionSecurityPriorityStatus()
        {
            UserDefinitionSecurityTeamWorks = new List<UserDefinitionSecurityTeamWork>();
        }
    }

}
// </auto-generated>
