// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.ODSViews;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // View_MIS_EmployeeSecurity
    public class ViewMisEmployeeSecurityConfiguration : IEntityTypeConfiguration<ViewMisEmployeeSecurity>
    {
        public void Configure(EntityTypeBuilder<ViewMisEmployeeSecurity> builder)
        {
            builder.ToView("View_MIS_EmployeeSecurity", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.EmployeeNumber).HasColumnName(@"EmployeeNumber").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);

            builder.Property(x => x.TeamCode).HasColumnName(@"TeamCode").HasColumnType("numeric(4,0)").HasPrecision(4, 0).IsRequired(false);
            builder.Property(x => x.TeamTitle).HasColumnName(@"TeamTitle").HasColumnType("nvarchar(60)").IsRequired(false).HasMaxLength(60);
            builder.Property(x => x.AuthenticationSecurity).HasColumnName(@"AuthenticationSecurity").HasColumnType("numeric(1,0)").HasPrecision(1, 0).IsRequired(false);
            builder.Property(x => x.DisplaySecurity).HasColumnName(@"DisplaySecurity").HasColumnType("numeric(1,0)").HasPrecision(1, 0).IsRequired(false);
            builder.Property(x => x.WindowsUser).HasColumnName(@"WindowsUser").HasColumnType("nvarchar(20)").IsRequired(false).HasMaxLength(20);
            builder.Property(x => x.TeamWorkId).HasColumnName(@"TeamWorkId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TeamWorkIsActive).HasColumnName(@"TeamWorkIsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.MisUser).HasColumnName(@"MisUser").HasColumnType("nvarchar(8)").IsRequired(false).HasMaxLength(8);
        }
    }

}
// </auto-generated>
