// <auto-generated>
// ReSharper disable All

using Ksc.Hr.Domain.Entities;
using Ksc.HR.Domain.Entities.Personal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // View_MonthlyAttendItemReport
    public class ViewMonthlyAttendItemReportConfiguration : IEntityTypeConfiguration<ViewEmployeeTeamUserActive>
    {
        public void Configure(EntityTypeBuilder<ViewEmployeeTeamUserActive> builder)
        {
            builder.ToView("ViewEmployeeTeamUserActive", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.EmployeeNumber).HasColumnName(@"EmployeeNumber").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.EmployeeName).HasColumnName(@"EmployeeName").HasColumnType("nvarchar(1001)").IsRequired().HasMaxLength(1001);
            builder.Property(x => x.WindowsUser).HasColumnName(@"WindowsUser").HasColumnType("nvarchar(20)").IsRequired(false).HasMaxLength(20);
            builder.Property(x => x.DisplaySecurity).HasColumnName(@"DisplaySecurity").HasColumnType("numeric(1,0)").HasPrecision(1, 0).IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.TeamStartDate).HasColumnName(@"TeamStartDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.TeamEndDate).HasColumnName(@"TeamEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(500)").IsRequired().HasMaxLength(500);
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
