// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.ODSViews;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // View_ODS_JobStatusCategory
    public class ViewOdsJobStatusCategoryConfiguration : IEntityTypeConfiguration<ViewOdsJobStatusCategory>
    {
        public void Configure(EntityTypeBuilder<ViewOdsJobStatusCategory> builder)
        {
            builder.ToView("View_ODS_JobStatusCategory", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.CategoryId).HasColumnName(@"CategoryId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.CategoryTitle).HasColumnName(@"CategoryTitle").HasColumnType("varchar(5)").IsRequired(false).IsUnicode(false).HasMaxLength(5);
        }
    }

}
// </auto-generated>
