using System;
using System.Collections.Generic;
using System.Text;

namespace Ksc.HR.DTO.Personal.MonthTimeSheet
{
    public class ReportMonthTimeSheet
    {
        public string EmployeeNumber { get; set; }
        public string FullFamily { get; set; }
        public string FatherName { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public string Code3 { get; set; }
        public string Code4 { get; set; }
        public string Code5 { get; set; }
        public string Code6 { get; set; }
        public string Code7 { get; set; }
        public string Code8 { get; set; }
        public string Code9 { get; set; }
        public string Code10 { get; set; }
        public string Code11 { get; set; }
        public string Code12 { get; set; }
        public string Code13 { get; set; }
        public string Code14 { get; set; }
        public string Code15 { get; set; }
        public string Code16 { get; set; }
        public string Code17 { get; set; }
        public string Code18 { get; set; }
        public string Code19 { get; set; }
        public string Code20 { get; set; }
        public string Code21 { get; set; }
        public string Code22 { get; set; }
        public string Code23 { get; set; }
        public string Code24 { get; set; }
        public string Code25 { get; set; }
        public string Code26 { get; set; }
        public string Code27 { get; set; }
        public string Code28 { get; set; }
        public string Code29 { get; set; }
        public string Code30 { get; set; }
        public string Code31 { get; set; }
        public string Code32 { get; set; }
        public string Code33 { get; set; }
        public string Code34 { get; set; }
        public string Code35 { get; set; }
        public string Code36 { get; set; }
        public string Code37 { get; set; }
        public string Code38 { get; set; }
        public string Code39 { get; set; }
        public string Code40 { get; set; }
        public string Code41 { get; set; }
        public string Code42 { get; set; }
        public string Code43 { get; set; }
        public string Code44 { get; set; }
        public string Code45 { get; set; }
        public string Code46 { get; set; }
        public string Code47 { get; set; }
        public string Code48 { get; set; }
        public string Code49 { get; set; }
        public string Code50 { get; set; }
        public string Code51 { get; set; }
        public string Code52 { get; set; }
        public string Code53 { get; set; }
        public string Code54 { get; set; }
        public string Code55 { get; set; }
        public string Code56 { get; set; }
        public string Code57 { get; set; }
        public string Code58 { get; set; }
        public string Code59 { get; set; }
        public string Code60 { get; set; }
        public string Code61 { get; set; }
        public string Code62 { get; set; }
        public string Code63 { get; set; }
        public string Code64 { get; set; }
        public string Code65 { get; set; }
        public string Code66 { get; set; }
        public string Code67 { get; set; }
        public string Code68 { get; set; }
        public string Code69 { get; set; }
        public string Code70 { get; set; }
        public string Code71 { get; set; }
        public string Code72 { get; set; }
        public string Code73 { get; set; }
        public string Code74 { get; set; }
        public string Code75 { get; set; }
        public string Code76 { get; set; }
        public string Code77 { get; set; }
        public string Code78 { get; set; }
        public string Code79 { get; set; }
        public string Code80 { get; set; }
        public string Code81 { get; set; }
        public string Code82 { get; set; }
        public string Code83 { get; set; }
        public string Code84 { get; set; }
        public string Code85 { get; set; }
        public string Code86 { get; set; }
        public string Code87 { get; set; }
        public string Code88 { get; set; }
        public string Code89 { get; set; }
        public string Code90 { get; set; }
        public string Code91 { get; set; }
        public string Code92 { get; set; }
        public string Code93 { get; set; }
        public string Code94 { get; set; }
        public string Code95 { get; set; }
        public string Code96 { get; set; }
        public string Code97 { get; set; }
        public string Code98 { get; set; }
        public string Code99 { get; set; }
        public string Code100 { get; set; }
        public string Code101 { get; set; }
        public string Code102 { get; set; }
        public string Code103 { get; set; }
        public string Code104 { get; set; }
        public string NationalCode { get; set; }
    }
}
