// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations

{
    // UserDefinitionSecurityPriorityStatus
    public class UserDefinitionSecurityPriorityStatusConfiguration : IEntityTypeConfiguration<UserDefinitionSecurityPriorityStatus>
    {
        public void Configure(EntityTypeBuilder<UserDefinitionSecurityPriorityStatus> builder)
        {
            builder.ToTable("UserDefinitionSecurityPriorityStatus", "Security");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeSecurityPriorityStatus").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
