// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    // AdditionalCostFood
    /// <summary>
    /// هزینه های جانبی هر پرس غذا
    /// </summary>
    public class AdditionalCostFood
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid AdditionalCostId { get; set; } // AdditionalCostId
        public Guid FoodProviderId { get; set; } // FoodProviderId
        public double Ratio { get; set; } // Ratio
        public double Cost { get; set; } // Cost

        // Foreign keys

        /// <summary>
        /// Parent AdditionalCost pointed by [AdditionalCostFood].([AdditionalCostId]) (FK_AdditionalCostFood_AdditionalCosts)
        /// </summary>
        public AdditionalCost AdditionalCost { get; set; } // FK_AdditionalCostFood_AdditionalCosts

        /// <summary>
        /// Parent FoodProvider pointed by [AdditionalCostFood].([FoodProviderId]) (FK_AdditionalCostFood_FoodProviders)
        /// </summary>
        public FoodProvider FoodProvider { get; set; } // FK_AdditionalCostFood_FoodProviders

        public AdditionalCostFood()
        {
            Id = Guid.NewGuid();
            Ratio = 1;
        }
    }
}