// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    /// <summary>
    /// غذاهای ارائه شده
    /// </summary>
    public partial class FoodProvider
    {
        public FoodProvider()
        {
            AdditionalCostFoods = new HashSet<AdditionalCostFood>();
            IngredinsFoods = new HashSet<IngredinsFood>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid ContractCompanyId { get; set; }
        public Guid FoodStuffId { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "date")]
        public DateTime InsertDate { get; set; }

        [ForeignKey("ContractCompanyId")]
        public virtual ContractingCompany ContractCompany { get; set; }
        [ForeignKey("FoodStuffId")]
        public virtual FoodStuff FoodStuff { get; set; }
       
        public virtual ICollection<AdditionalCostFood> AdditionalCostFoods { get; set; }
      
        public virtual ICollection<IngredinsFood> IngredinsFoods { get; set; }
    }
}