// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    /// <summary>
    /// مواد غذایی
    /// </summary>
    [Table("FoodStuff")]
    public partial class FoodStuff
    {
        public FoodStuff()
        {
            FoodProviders = new HashSet<FoodProvider>();
            StuffPrices = new HashSet<StuffPrice>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(500)]
        public string Title { get; set; }
        public int? Amount { get; set; }
        public int? Calories { get; set; }
        public Guid? FoodCategoryId { get; set; }

        [ForeignKey("FoodCategoryId")]
        [InverseProperty("FoodStuffs")]
        public virtual FoodCategory FoodCategory { get; set; }
        [InverseProperty("FoodStuff")]
        public virtual ICollection<FoodProvider> FoodProviders { get; set; }
        [InverseProperty("FoodStuff")]
        public virtual ICollection<StuffPrice> StuffPrices { get; set; }
    }
}