// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    /// <summary>
    /// مواد غذایی
    /// </summary>

    public class FoodStuff
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public long? FoodCategoryId { get; set; } // FoodCategoryId

        // Reverse navigation

        /// <summary>
        /// Child FoodProviders where [FoodProviders].[FoodStuffId] point to this entity (FK_FoodProviders_FoodStuff)
        /// </summary>
        public ICollection<FoodProvider> FoodProviders { get; set; } // FoodProviders.FK_FoodProviders_FoodStuff

        /// <summary>
        /// Child StuffPrices where [StuffPrice].[FoodStuffId] point to this entity (FK_StuffPrice_FoodStuff)
        /// </summary>
        public ICollection<StuffPrice> StuffPrices { get; set; } // StuffPrice.FK_StuffPrice_FoodStuff

        // Foreign keys

        /// <summary>
        /// Parent FoodCategory pointed by [FoodStuff].([FoodCategoryId]) (FK_FoodStuff_FoodCategory)
        /// </summary>
        public FoodCategory FoodCategory { get; set; } // FK_FoodStuff_FoodCategory

        public FoodStuff()
        {
            Id = Guid.NewGuid();
            FoodProviders = new List<FoodProvider>();
            StuffPrices = new List<StuffPrice>();
        }
    }
}