// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    // IngredinsFood
    /// <summary>
    /// مواد لازم
    /// </summary>
    public class IngredinsFood
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid StuffPriceId { get; set; } // StuffPriceId
        public Guid FoodProviderId { get; set; } // FoodProviderId
        public double? Amount { get; set; } // Amount
        public double? Cost { get; set; } // Cost
        public string Unit { get; set; } // Unit

        // Foreign keys

        /// <summary>
        /// Parent FoodProvider pointed by [IngredinsFood].([FoodProviderId]) (FK_IngredinsFood_FoodProviders)
        /// </summary>
        public FoodProvider FoodProvider { get; set; } // FK_IngredinsFood_FoodProviders

        /// <summary>
        /// Parent StuffPrice pointed by [IngredinsFood].([StuffPriceId]) (FK_IngredinsFood_StuffPrice)
        /// </summary>
        public StuffPrice StuffPrice { get; set; } // FK_IngredinsFood_StuffPrice

        public IngredinsFood()
        {
            Id = Guid.NewGuid();
        }
    }
}