// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChefHesab.Domain;


namespace ChefHesab.Domain
{
    /// <summary>
    /// مواد لازم
    /// </summary>
    [Table("IngredinsFood")]
    public partial class IngredinsFood
    {
        [Key]
        public Guid Id { get; set; }
        public Guid StuffPriceId { get; set; }
        public Guid FoodProviderId { get; set; }
        public double? Amount { get; set; }
        public double? Cost { get; set; }

        [ForeignKey("FoodProviderId")]
        [InverseProperty("IngredinsFoods")]
        public virtual FoodProvider FoodProvider { get; set; }
        [ForeignKey("StuffPriceId")]
        [InverseProperty("IngredinsFoods")]
        public virtual StuffPrice StuffPrice { get; set; }
    }
}