// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using KSC.Domain;
namespace Ksc.HR.Domain.Entities.WorkFlow
{
    // ValidJobCategory
    public class WF_ValidJobCategory : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string JobStatusCode { get; set; } // JobStatusCode (length: 2)
        public int JobCategoryRangeId { get; set; } // JobCategoryRangeId
        public string JobCategoryCode { get; set; } // JobCategoryCode (length: 2)
        public int SortNumber { get; set; } // SortNumber
        public bool IsActive { get; set; } // IsActive
        // Foreign keys

        /// <summary>
        /// Parent WF_JobCategoryRange pointed by [ValidJobCategory].([JobCategoryRangeId]) (FK_WF_ValidJobCategory_WF_JobCategoryRange)
        /// </summary>
        public virtual WF_JobCategoryRange WF_JobCategoryRange { get; set; } // FK_WF_ValidJobCategory_WF_JobCategoryRange
    }

}
// </auto-generated>
