// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using KSC.Domain;
namespace Ksc.HR.Domain.Entities.WorkFlow
{
    // WorkFlowStatusReason
    public class WF_WorkFlowStatusReason : IEntityBase<int>
    {
        /// <summary>
        /// شناسه دلیل تغییر وضعیت گردش درخواست
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// مدیریت گزدش درخواست
        /// </summary>
        public int WorkFlowManagementId { get; set; } // WorkFlowManagementId

        /// <summary>
        /// دلیل تغییر وضعیت
        /// </summary>
        public int StatusReasonId { get; set; } // StatusReasonId

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        /// <summary>
        /// تاریخ ثبت
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر ثبت کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent WF_StatusReason pointed by [WorkFlowStatusReason].([StatusReasonId]) (FK_WF_WorkFlowStatusReason_WF_StatusReason)
        /// </summary>
        public virtual WF_StatusReason WF_StatusReason { get; set; } // FK_WF_WorkFlowStatusReason_WF_StatusReason

        /// <summary>
        /// Parent WF_WorkFlowManagement pointed by [WorkFlowStatusReason].([WorkFlowManagementId]) (FK_WF_WorkFlowStatusReason_WF_WorkFlowManagement)
        /// </summary>
        public virtual WF_WorkFlowManagement WF_WorkFlowManagement { get; set; } // FK_WF_WorkFlowStatusReason_WF_WorkFlowManagement
    }

}
// </auto-generated>
