// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Chart;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations.Chart
{
    // JobGroup
    public class JobGroupConfiguration : IEntityTypeConfiguration<JobGroup>
    {
        public void Configure(EntityTypeBuilder<JobGroup> builder)
        {
            builder.ToTable("JobGroup", "Chart");
            builder.HasKey(x => x.Id).HasName("PK_JobGroup").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Score).HasColumnName(@"Score").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.VariableCoefficient).HasColumnName(@"VariableCoefficient").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.MinBaseAmountYears).HasColumnName(@"MinBaseAmountYears").HasColumnType("bigint").IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Year).HasColumnName(@"Year").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Chart_CategoryCoefficient).WithMany(b => b.Chart_JobGroups).HasForeignKey(c => c.CategoryCoefficientId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_JobGroup_CategoryCoefficient");

        }
    }

}
// </auto-generated>
