// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.Hr.Data.Persistant.Configurations
{
    // DependenceJob
    public class EmployeeAccountBankConfiguration : IEntityTypeConfiguration<EmployeeAccountBank>
    {
        public void Configure(EntityTypeBuilder<EmployeeAccountBank> builder)
        {
            builder.ToTable("EmployeeAccountBank", "Emp");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeAccountBank").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.FamilyId).HasColumnName(@"FamilyId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.NationalCode).HasColumnName(@"NationalCode").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20);
            builder.Property(x => x.BankId).HasColumnName(@"BankId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AccountBankTypeId).HasColumnName(@"AccountBankTypeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.AccountNumber).HasColumnName(@"AccountNumber").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.CardNumber).HasColumnName(@"CardNumber").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();

            builder.Property(x => x.EntityId).HasColumnName(@"EntityId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.EmployeeAccountBanks).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeAccountBank_Employee");
            builder.HasOne(a => a.AccountBankType).WithMany(b => b.EmployeeAccountBanks).HasForeignKey(c => c.AccountBankTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeAccountBank_AccountBankType");


        }
    }

}
// </auto-generated>
