// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // CompatibleRollCall
    /// <summary>
    /// کدهای حضور غیاب سازگار
    /// </summary>
    public class CompatibleRollCall : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int RollCallDefinitionId { get; set; } // RollCallDefinitionId
        public int CompatibleRollCallId { get; set; } // CompatibleRollCallId

        /// <summary>
        /// نوع تبدیل کد
        /// </summary>
        public int CompatibleRollCallType { get; set; } // CompatibleRollCallType
        public int? DayNumber { get; set; } // DayNumber
        public int? WorkDayTypeId { get; set; } // WorkDayTypeId
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Foreign keys

        /// <summary>
        /// Parent RollCallDefinition pointed by [CompatibleRollCall].([CompatibleRollCallId]) (FK_CompatibleRollCall_RollCallDefinition1)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition_CompatibleRollCallId { get; set; } // FK_CompatibleRollCall_RollCallDefinition1

        /// <summary>
        /// Parent RollCallDefinition pointed by [CompatibleRollCall].([RollCallDefinitionId]) (FK_CompatibleRollCall_RollCallDefinition)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition_RollCallDefinitionId { get; set; } // FK_CompatibleRollCall_RollCallDefinition

        /// <summary>
        /// Parent WorkDayType pointed by [CompatibleRollCall].([WorkDayTypeId]) (FK_CompatibleRollCall_WorkDayType)
        /// </summary>
        public virtual WorkDayType WorkDayType { get; set; } // FK_CompatibleRollCall_WorkDayType

    }

}
// </auto-generated>
