// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KSC.Domain;
using System;
using System.Collections.Generic;

namespace Ksc.HR.Domain.Entities.Workshift
{
    /// <summary>
    /// تنظیمات ساعت شروع و پایان در روز و شب
    /// </summary>
    public partial class DayNightSettingTime : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string StartTime { get; set; } // StartTime (length: 5)
        public string EndTime { get; set; } // EndTime (length: 5)

        /// <summary>
        /// روز است؟
        /// </summary>
        public bool IsDay { get; set; } // IsDay
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child DayNightPercentEmplymentTypes where [DayNightPercentEmplymentType].[DayNightSettingTimeId] point to this entity (FK_DayNightPercentEmplymentType_DayNightSettingTime)
        /// </summary>
        public virtual ICollection<DayNightPercentEmplymentType> DayNightPercentEmplymentTypes { get; set; } // DayNightPercentEmplymentType.FK_DayNightPercentEmplymentType_DayNightSettingTime

        /// <summary>
        /// Child DayNightRollCalls where [DayNightRollCall].[DayNightSettingTimeId] point to this entity (FK_DayNightRollCall_DayNightSettingTime)
        /// </summary>
        public virtual ICollection<DayNightRollCall> DayNightRollCalls { get; set; } // DayNightRollCall.FK_DayNightRollCall_DayNightSettingTime

        public DayNightSettingTime()
        {
            DayNightPercentEmplymentTypes = new List<DayNightPercentEmplymentType>();
            DayNightRollCalls = new List<DayNightRollCall>();
        }
    }
}