// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // DayNightRollCall
    /// <summary>
    /// تنظیمات ساعت شروع و پایان در روز و شب با کد حضور-غیاب
    /// </summary>
    public class DayNightRollCall : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int DayNightSettingTimeId { get; set; } // DayNightSettingTimeId

        /// <summary>
        /// شماره روز
        /// </summary>
        public int DayNumber { get; set; } // DayNumber
        public int RollCallDefinitionId { get; set; } // RollCallDefinitionId

        /// <summary>
        /// ضریب
        /// </summary>
        public double PercentAmount { get; set; } // PercentAmount
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent DayNightSettingTime pointed by [DayNightRollCall].([DayNightSettingTimeId]) (FK_DayNightRollCall_DayNightSettingTime)
        /// </summary>
        public virtual DayNightSettingTime DayNightSettingTime { get; set; } // FK_DayNightRollCall_DayNightSettingTime

        /// <summary>
        /// Parent RollCallDefinition pointed by [DayNightRollCall].([RollCallDefinitionId]) (FK_DayNightRollCall_RollCallDefinition)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition { get; set; } // FK_DayNightRollCall_RollCallDefinition
    }

}
// </auto-generated>
