// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // DayNightPercentEmplymentType
    /// <summary>
    /// تنظیمات ساعت شروع و پایان در روز و شب با نوع استخدام
    /// </summary>
    public class DayNightPercentEmplymentType : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmplymentTypeId { get; set; } // EmplymentTypeId
        public int DayNightSettingTimeId { get; set; } // DayNightSettingTimeId

        /// <summary>
        /// ضریب فراخوان
        /// </summary>
        public double OnCallPercent { get; set; } // OnCallPercent
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent DayNightSettingTime pointed by [DayNightPercentEmplymentType].([DayNightSettingTimeId]) (FK_DayNightPercentEmplymentType_DayNightSettingTime)
        /// </summary>
        public virtual DayNightSettingTime DayNightSettingTime { get; set; } // FK_DayNightPercentEmplymentType_DayNightSettingTime
    }

}
// </auto-generated>
