// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KSC.Domain;
using System;
using System.Collections.Generic;

namespace Ksc.HR.Domain.Entities.Workshift
{
    /// <summary>
    /// استان
    /// </summary>
    public partial class Province : IEntityBase<int>
    {
        public Province()
        {
            City = new HashSet<City>();
        }

        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string? EnglishTitle { get; set; }
        public string Code { get; set; } = null!;
        public int? CountryId { get; set; }
        public DateTime? InsertDate { get; set; }
        public string? InsertUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string? UpdateUser { get; set; }
        public byte[] RowVersion { get; set; } = null!;

        public virtual Country Country { get; set; } //= null!;
        public virtual ICollection<City> City { get; set; }
    }
}