// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // RollCallEmploymentType
    /// <summary>
    /// ارتباط کد حضورغیاب و نوع استخدام
    /// </summary>
    public class RollCallEmploymentType : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// کد حضورغیاب
        /// </summary>
        public int RollCallDefinitionId { get; set; } // RollCallDefinitionId

        /// <summary>
        /// نوع استخدام
        /// </summary>
        public decimal EmploymentTypeCode { get; set; } // EmploymentTypeCode
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Foreign keys

        /// <summary>
        /// Parent RollCallDefinition pointed by [RollCallEmploymentType].([RollCallDefinitionId]) (FK_RollCallEmploymentType_RollCallDefinition)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition { get; set; } // FK_RollCallEmploymentType_RollCallDefinition
    }

}
// </auto-generated>
