// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // RollCallJobCategory
    /// <summary>
    /// جدول واسط رده شغلی و  کدهای حضور غیاب
    /// </summary>
    public class RollCallJobCategory : IEntityBase<int>
    {
        public RollCallJobCategory()
        {

        }
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// شناسه حضور و غیاب
        /// </summary>
        public int RollCallDefinitionId { get; set; } // RollCallDefinitionId

        /// <summary>
        /// رده شغلی
        /// </summary>
        public string CodeCategoryJobCategory { get; set; } // CodeCategoryJobCategory (length: 2)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Foreign keys

        /// <summary>
        /// Parent RollCallDefinition pointed by [RollCallJobCategory].([RollCallDefinitionId]) (FK_RollCallJobCategory_RollCallDefinition)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition { get; set; } // FK_RollCallJobCategory_RollCallDefinition
    }

}
// </auto-generated>
