// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // RollCallConcept
    /// <summary>
    /// ماهیت کدهای حضور غیاب
    /// </summary>
    public class RollCallConcept : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 500)

        /// <summary>
        /// کد
        /// </summary>
        public string Code { get; set; } // Code (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child RollCallDefinitions where [RollCallDefinition].[RollCallConceptId] point to this entity (FK_RollCallDefinition_RollCallConcept)
        /// </summary>
        public virtual ICollection<RollCallDefinition> RollCallDefinitions { get; set; } // RollCallDefinition.FK_RollCallDefinition_RollCallConcept

        public RollCallConcept()
        {
            RollCallDefinitions = new List<RollCallDefinition>();
        }

    }

}
// </auto-generated>
