// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // SacrificePercentageSetting
    public class SacrificePercentageSetting : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// حداقل درصد ایثارگری
        /// </summary>
        public int MinimumPercentage { get; set; } // MinimumPercentage

        /// <summary>
        /// حداکثر درصد ایثارگری
        /// </summary>
        public int MaximumPercentage { get; set; } // MaximumPercentage

        /// <summary>
        /// فرجه زمانی در حضور-غیاب
        /// </summary>
        public string AttendAbsenceTolerance { get; set; } // AttendAbsenceTolerance (length: 5)

        /// <summary>
        /// ضریب مرخصی جانبازی
        /// </summary>
        public decimal? VacationVeteranFactor { get; set; }
    }

}
// </auto-generated>
