// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // TeamWorkCategory
    /// <summary>
    /// دسته بندی تیم کاری
    /// </summary>
    public class TeamWorkCategory : IEntityBase<int>
    {
        public TeamWorkCategory()
        {
            TeamWorks = new HashSet<TeamWork>();
        }
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 500)

        /// <summary>
        /// کد
        /// </summary>
        public string Code { get; set; } // Code (length: 50)
        public decimal CostCenter { get; set; }  
        public int TeamWorkCategoryTypeId { get; set; } // TeamWorkCategoryTypeId
        public int TeamWorkMangementCodeId { get; set; } // TeamWorkMangementCodeId
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child TeamWorks where [TeamWork].[TeamWorkCategoryId] point to this entity (FK_TeamWork_TeamWorkCategory)
        /// </summary>
        public virtual ICollection<TeamWork> TeamWorks { get; set; } // TeamWork.FK_TeamWork_TeamWorkCategory

        // Foreign keys

        /// <summary>
        /// Parent TeamWorkCategoryType pointed by [TeamWorkCategory].([TeamWorkCategoryTypeId]) (FK_TeamWorkCategory_TeamWorkCategoryType)
        /// </summary>
        public virtual TeamWorkCategoryType TeamWorkCategoryType_TeamWorkCategoryTypeId { get; set; } // FK_TeamWorkCategory_TeamWorkCategoryType

        /// <summary>
        /// Parent TeamWorkMangementCode pointed by [TeamWorkCategory].([TeamWorkMangementCodeId]) (FK_TeamWorkCategory_TeamWorkMangementCode)
        /// </summary>
        public virtual TeamWorkMangementCode TeamWorkMangementCode_TeamWorkMangementCodeId { get; set; } // FK_TeamWorkCategory_TeamWorkMangementCode

    }

}
// </auto-generated>
