// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;

namespace Ksc.HR.Domain.Entities.Workshift
{
    // UnofficialHolidayReason
    /// <summary>
    /// تعطیلات غیررسمی
    /// </summary>
    public class UnofficialHolidayReason : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 500)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string DomainName { get; set; } // DomainName (length: 50)
        public bool IsActive { get; set; } // IsActive
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child WorkCompanyUnOfficialHolidaySettings where [WorkCompanyUnOfficialHolidaySetting].[UnofficialHolidayReasonId] point to this entity (FK_WorkCompanyUnOfficialHolidaySetting_UnofficialHolidayReason)
        /// </summary>
        public virtual ICollection<WorkCompanyUnOfficialHolidaySetting> WorkCompanyUnOfficialHolidaySettings { get; set; } // WorkCompanyUnOfficialHolidaySetting.FK_WorkCompanyUnOfficialHolidaySetting_UnofficialHolidayReason

        public UnofficialHolidayReason()
        {
            WorkCompanyUnOfficialHolidaySettings = new List<WorkCompanyUnOfficialHolidaySetting>();
        }
    }

}
// </auto-generated>
