//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "S6PSN017.dtd")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace = "S6PSN017.dtd", IsNullable = false)]
namespace Ksc.HR.DTO.MIS
{
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "S6XML108.dtd")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "S6XML108.dtd", IsNullable = false)]
    [XmlRoot("RPC108")]
    public partial class RPC108
    {

        public bool IsError { get; set; }
        public string MsgError { get; set; }

        private string oPERATIONField;

        private string nUM_PRSN_EMPLField;

        private string cOD_STA_PYM_EMPLField;

        private string dAT_STA_PYM_EMPLField;

        private string nAM_PER_EMPLField;

        private string nAM_FAM_EMPLField;

        private string nAM_PER_LST_EMPLField;

        private string nAM_FAM_LST_EMPLField;

        private string cOD_SEX_EMPLField;

        private string nAM_FTHR_EMPLField;

        private string nUM_NNAL_EMPLField;

        private string nUM_CRT_EMPLField;

        private string cOD_NNLTY_EMPLField;

        private string cOD_RLGN_EMPLField;

        private string dAT_BRT_EMPLField;

        private string cOD_CITY_BORNField;

        private string cOD_RGN_CITY_BORNField;

        private string cOD_CNTRY_CITY_BORNField;

        private string dAT_ISSU_CRT_EMPLField;

        private string cOD_CITY_DOCField;

        private string cOD_RGN_CITY_DOCField;

        private string cOD_CNTRY_CITY_DOCField;

        private string cOD_MLTRY_EMPLField;

        private string dAT_STR_MLTRY_EMPLField;

        private string dAT_END_MLTRY_EMPLField;

        private string cOD_MRD_EMPLField;

        private string dAT_MRD_EMPLField;

        private string nUM_PNS_EMPLField;

        private string fK_TBPNSField;

        private string cOD_INSU_COMP_EMPLField;

        private string nUM_MOBIL_EMPLField;

        private string cOD_BLD_TYP_EMPLField;

        private string cOD_ZIP_EMPLField;

        private string cOD_CITY_RSDNCField;

        private string cOD_RGN_CITY_RSDNCField;

        private string cOD_CNTRY_CITY_RSDNCField;

        private string dES_ADR_EMPLField;

        private string uSER_NAMEField;

        /// <remarks/>
        public string OPERATION
        {
            get
            {
                return this.oPERATIONField;
            }
            set
            {
                this.oPERATIONField = value;
            }
        }

        /// <remarks/>
        public string NUM_PRSN_EMPL
        {
            get
            {
                return this.nUM_PRSN_EMPLField;
            }
            set
            {
                this.nUM_PRSN_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_STA_PYM_EMPL
        {
            get
            {
                return this.cOD_STA_PYM_EMPLField;
            }
            set
            {
                this.cOD_STA_PYM_EMPLField = value;
            }
        }

        /// <remarks/>
        public string DAT_STA_PYM_EMPL
        {
            get
            {
                return this.dAT_STA_PYM_EMPLField;
            }
            set
            {
                this.dAT_STA_PYM_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NAM_PER_EMPL
        {
            get
            {
                return this.nAM_PER_EMPLField;
            }
            set
            {
                this.nAM_PER_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NAM_FAM_EMPL
        {
            get
            {
                return this.nAM_FAM_EMPLField;
            }
            set
            {
                this.nAM_FAM_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NAM_PER_LST_EMPL
        {
            get
            {
                return this.nAM_PER_LST_EMPLField;
            }
            set
            {
                this.nAM_PER_LST_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NAM_FAM_LST_EMPL
        {
            get
            {
                return this.nAM_FAM_LST_EMPLField;
            }
            set
            {
                this.nAM_FAM_LST_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_SEX_EMPL
        {
            get
            {
                return this.cOD_SEX_EMPLField;
            }
            set
            {
                this.cOD_SEX_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NAM_FTHR_EMPL
        {
            get
            {
                return this.nAM_FTHR_EMPLField;
            }
            set
            {
                this.nAM_FTHR_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NUM_NNAL_EMPL
        {
            get
            {
                return this.nUM_NNAL_EMPLField;
            }
            set
            {
                this.nUM_NNAL_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NUM_CRT_EMPL
        {
            get
            {
                return this.nUM_CRT_EMPLField;
            }
            set
            {
                this.nUM_CRT_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_NNLTY_EMPL
        {
            get
            {
                return this.cOD_NNLTY_EMPLField;
            }
            set
            {
                this.cOD_NNLTY_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_RLGN_EMPL
        {
            get
            {
                return this.cOD_RLGN_EMPLField;
            }
            set
            {
                this.cOD_RLGN_EMPLField = value;
            }
        }

        /// <remarks/>
        public string DAT_BRT_EMPL
        {
            get
            {
                return this.dAT_BRT_EMPLField;
            }
            set
            {
                this.dAT_BRT_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_CITY_BORN
        {
            get
            {
                return this.cOD_CITY_BORNField;
            }
            set
            {
                this.cOD_CITY_BORNField = value;
            }
        }

        /// <remarks/>
        public string COD_RGN_CITY_BORN
        {
            get
            {
                return this.cOD_RGN_CITY_BORNField;
            }
            set
            {
                this.cOD_RGN_CITY_BORNField = value;
            }
        }

        /// <remarks/>
        public string COD_CNTRY_CITY_BORN
        {
            get
            {
                return this.cOD_CNTRY_CITY_BORNField;
            }
            set
            {
                this.cOD_CNTRY_CITY_BORNField = value;
            }
        }

        /// <remarks/>
        public string DAT_ISSU_CRT_EMPL
        {
            get
            {
                return this.dAT_ISSU_CRT_EMPLField;
            }
            set
            {
                this.dAT_ISSU_CRT_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_CITY_DOC
        {
            get
            {
                return this.cOD_CITY_DOCField;
            }
            set
            {
                this.cOD_CITY_DOCField = value;
            }
        }

        /// <remarks/>
        public string COD_RGN_CITY_DOC
        {
            get
            {
                return this.cOD_RGN_CITY_DOCField;
            }
            set
            {
                this.cOD_RGN_CITY_DOCField = value;
            }
        }

        /// <remarks/>
        public string COD_CNTRY_CITY_DOC
        {
            get
            {
                return this.cOD_CNTRY_CITY_DOCField;
            }
            set
            {
                this.cOD_CNTRY_CITY_DOCField = value;
            }
        }

        /// <remarks/>
        public string COD_MLTRY_EMPL
        {
            get
            {
                return this.cOD_MLTRY_EMPLField;
            }
            set
            {
                this.cOD_MLTRY_EMPLField = value;
            }
        }

        /// <remarks/>
        public string DAT_STR_MLTRY_EMPL
        {
            get
            {
                return this.dAT_STR_MLTRY_EMPLField;
            }
            set
            {
                this.dAT_STR_MLTRY_EMPLField = value;
            }
        }

        /// <remarks/>
        public string DAT_END_MLTRY_EMPL
        {
            get
            {
                return this.dAT_END_MLTRY_EMPLField;
            }
            set
            {
                this.dAT_END_MLTRY_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_MRD_EMPL
        {
            get
            {
                return this.cOD_MRD_EMPLField;
            }
            set
            {
                this.cOD_MRD_EMPLField = value;
            }
        }

        /// <remarks/>
        public string DAT_MRD_EMPL
        {
            get
            {
                return this.dAT_MRD_EMPLField;
            }
            set
            {
                this.dAT_MRD_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NUM_PNS_EMPL
        {
            get
            {
                return this.nUM_PNS_EMPLField;
            }
            set
            {
                this.nUM_PNS_EMPLField = value;
            }
        }

        /// <remarks/>
        public string FK_TBPNS
        {
            get
            {
                return this.fK_TBPNSField;
            }
            set
            {
                this.fK_TBPNSField = value;
            }
        }

        /// <remarks/>
        public string COD_INSU_COMP_EMPL
        {
            get
            {
                return this.cOD_INSU_COMP_EMPLField;
            }
            set
            {
                this.cOD_INSU_COMP_EMPLField = value;
            }
        }

        /// <remarks/>
        public string NUM_MOBIL_EMPL
        {
            get
            {
                return this.nUM_MOBIL_EMPLField;
            }
            set
            {
                this.nUM_MOBIL_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_BLD_TYP_EMPL
        {
            get
            {
                return this.cOD_BLD_TYP_EMPLField;
            }
            set
            {
                this.cOD_BLD_TYP_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_ZIP_EMPL
        {
            get
            {
                return this.cOD_ZIP_EMPLField;
            }
            set
            {
                this.cOD_ZIP_EMPLField = value;
            }
        }

        /// <remarks/>
        public string COD_CITY_RSDNC
        {
            get
            {
                return this.cOD_CITY_RSDNCField;
            }
            set
            {
                this.cOD_CITY_RSDNCField = value;
            }
        }

        /// <remarks/>
        public string COD_RGN_CITY_RSDNC
        {
            get
            {
                return this.cOD_RGN_CITY_RSDNCField;
            }
            set
            {
                this.cOD_RGN_CITY_RSDNCField = value;
            }
        }

        /// <remarks/>
        public string COD_CNTRY_CITY_RSDNC
        {
            get
            {
                return this.cOD_CNTRY_CITY_RSDNCField;
            }
            set
            {
                this.cOD_CNTRY_CITY_RSDNCField = value;
            }
        }

        /// <remarks/>
        public string DES_ADR_EMPL
        {
            get
            {
                return this.dES_ADR_EMPLField;
            }
            set
            {
                this.dES_ADR_EMPLField = value;
            }
        }

        /// <remarks/>
        public string USER_NAME
        {
            get
            {
                return this.uSER_NAMEField;
            }
            set
            {
                this.uSER_NAMEField = value;
            }
        }
    }
}