//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
[XmlRoot("RPC_EMPLOYMENT")]
public partial class RPC_EMPLOYMENT
{
    /// <summary>
    /// شماره پرسنلی
    /// </summary>
    public string NUM_PRSN  { get; set; }
    /// <summary>
    /// کد وضعیت اشتغال
    /// </summary>
    public string COD_STA_PYM  { get; set; }
    /// <summary>
    /// نوع استخدام
    /// </summary>
    public string FK_EMPLT  { get; set; }
    /// <summary>
    /// وضعیت استخدام
    /// </summary>
    public string COD_CLASS  { get; set; }
    /// <summary>
    /// تاریخ  استخدام
    /// </summary>
    public string DAT_EMPLT  { get; set; }
    ///// <summary>
    ///// تاریخ شروع قرارداد
    ///// </summary>
    //public string DAT_STR_CNTRC  { get; set; }
    ///// <summary>
    ///// تاریخ پایان قرارداد
    ///// </summary>
    //public string DAT_END_CNTRC  { get; set; }
    ///// <summary>
    ///// زمان کاری
    ///// </summary>
    //public string COD_TYP_WRK  { get; set; }
    ///// <summary>
    ///// شیفت کاری - گروه کاری
    ///// </summary>
    //public string COD_WRK_GRP  { get; set; }
    /// <summary>
    /// نوع ثبت ورود و خروج
    /// </summary>
    public string COD_EXMP_ENEX { get; set; }
    /// <summary>
    /// کارکرد شناور؟
    /// </summary>
    public string FLG_FLOAT_ATABI { get; set; }
    ///// <summary>
    ///// کد تیم کاری
    ///// </summary>
    //public string NUM_TEAM  { get; set; }
    ///// <summary>
    ///// تاریخ شروع  در تیم
    ///// </summary>
    //public string DAT_STR_TEAM  { get; set; }
    /// <summary>
    /// کد مدرک تحصیلی
    /// </summary>
    public string COD_LEV_EDUC { get; set; }
    /// <summary>
    /// کد رشته تحصیلی
    /// </summary>
    public string COD_EXPRT_LEV { get; set; }
    /// <summary>
    /// تاریخ اخد مدرک
    /// </summary>
    public string DAT_STR_EDUC { get; set; }
    /// <summary>
    /// شهر محل خدمت
    /// </summary>
    public string FK_CITY_WORK { get; set; }
    ///// <summary>
    ///// کد پست 13 رقمی
    ///// </summary>
    //public string FK_JPOS  { get; set; }
    ///// <summary>
    ///// تاریخ احراز پست
    ///// </summary>
    //public string DAT_JOB_POS  { get; set; }
    /// <summary>
    /// کد نوع پس انداز
    /// </summary>
    public string FK_SAVTB { get; set; }
    /// <summary>
    /// مبنا پس انداز سال ماه
    /// </summary>
    public string DAT_STR_SAV { get; set; }
    /// <summary>
    /// کد وضعیت ایثارگری
    /// </summary>
    public string COD_ISAR { get; set; }
    /// <summary>
    /// درصد جانبازی
    /// </summary>
    public string PCN_ISAR { get; set; }
    /// <summary>
    /// کد ایثارگری
    /// </summary>
    public string COD_OVT_VAC { get; set; }
}

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="S6XML080.dtd")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="S6XML080.dtd", IsNullable=false)]
//public partial class RPC_EMPLOYMENT {
    
//    private string nUM_PRSNField;
    
//    private string cOD_STA_PYMField;
    
//    private string fK_EMPLTField;
    
//    private string cOD_CLASSField;
    
//    private string dAT_EMPLTField;
    
//    private string dAT_STR_CNTRCField;
    
//    private string dAT_END_CNTRCField;
    
//    private string cOD_TYP_WRKField;
    
//    private string cOD_WRK_GRPField;
    
//    private string cOD_EXMP_ENEXField;
    
//    private string fLG_FLOAT_ATABIField;
    
//    private string nUM_TEAMField;
    
//    private string dAT_STR_TEAMField;
    
//    private string cOD_LEV_EDUCField;
    
//    private string cOD_EXPRT_LEVField;
    
//    private string dAT_STR_EDUCField;
    
//    private string fK_CITY_WORKField;
    
//    private string fK_JPOSField;
    
//    private string dAT_JOB_POSField;
    
//    private string fK_SAVTBField;
    
//    private string[] dAT_STR_SAVField;
    
//    private string cOD_ISARField;
    
//    private string pCN_ISARField;
    
//    private string cOD_OVT_VACField;
    
//    /// <remarks/>
//    public string NUM_PRSN {
//        get {
//            return this.nUM_PRSNField;
//        }
//        set {
//            this.nUM_PRSNField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_STA_PYM {
//        get {
//            return this.cOD_STA_PYMField;
//        }
//        set {
//            this.cOD_STA_PYMField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string FK_EMPLT {
//        get {
//            return this.fK_EMPLTField;
//        }
//        set {
//            this.fK_EMPLTField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_CLASS {
//        get {
//            return this.cOD_CLASSField;
//        }
//        set {
//            this.cOD_CLASSField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_EMPLT {
//        get {
//            return this.dAT_EMPLTField;
//        }
//        set {
//            this.dAT_EMPLTField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_STR_CNTRC {
//        get {
//            return this.dAT_STR_CNTRCField;
//        }
//        set {
//            this.dAT_STR_CNTRCField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_END_CNTRC {
//        get {
//            return this.dAT_END_CNTRCField;
//        }
//        set {
//            this.dAT_END_CNTRCField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_TYP_WRK {
//        get {
//            return this.cOD_TYP_WRKField;
//        }
//        set {
//            this.cOD_TYP_WRKField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_WRK_GRP {
//        get {
//            return this.cOD_WRK_GRPField;
//        }
//        set {
//            this.cOD_WRK_GRPField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_EXMP_ENEX {
//        get {
//            return this.cOD_EXMP_ENEXField;
//        }
//        set {
//            this.cOD_EXMP_ENEXField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string FLG_FLOAT_ATABI {
//        get {
//            return this.fLG_FLOAT_ATABIField;
//        }
//        set {
//            this.fLG_FLOAT_ATABIField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string NUM_TEAM {
//        get {
//            return this.nUM_TEAMField;
//        }
//        set {
//            this.nUM_TEAMField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_STR_TEAM {
//        get {
//            return this.dAT_STR_TEAMField;
//        }
//        set {
//            this.dAT_STR_TEAMField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_LEV_EDUC {
//        get {
//            return this.cOD_LEV_EDUCField;
//        }
//        set {
//            this.cOD_LEV_EDUCField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_EXPRT_LEV {
//        get {
//            return this.cOD_EXPRT_LEVField;
//        }
//        set {
//            this.cOD_EXPRT_LEVField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_STR_EDUC {
//        get {
//            return this.dAT_STR_EDUCField;
//        }
//        set {
//            this.dAT_STR_EDUCField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string FK_CITY_WORK {
//        get {
//            return this.fK_CITY_WORKField;
//        }
//        set {
//            this.fK_CITY_WORKField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string FK_JPOS {
//        get {
//            return this.fK_JPOSField;
//        }
//        set {
//            this.fK_JPOSField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string DAT_JOB_POS {
//        get {
//            return this.dAT_JOB_POSField;
//        }
//        set {
//            this.dAT_JOB_POSField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string FK_SAVTB {
//        get {
//            return this.fK_SAVTBField;
//        }
//        set {
//            this.fK_SAVTBField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("DAT_STR_SAV")]
//    public string[] DAT_STR_SAV {
//        get {
//            return this.dAT_STR_SAVField;
//        }
//        set {
//            this.dAT_STR_SAVField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_ISAR {
//        get {
//            return this.cOD_ISARField;
//        }
//        set {
//            this.cOD_ISARField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string PCN_ISAR {
//        get {
//            return this.pCN_ISARField;
//        }
//        set {
//            this.pCN_ISARField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string COD_OVT_VAC {
//        get {
//            return this.cOD_OVT_VACField;
//        }
//        set {
//            this.cOD_OVT_VACField = value;
//        }
//    }
//}
