////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

using System.Xml.Serialization;
[XmlRoot("RPC_ACN_BANK")]
public partial class RPC_ACN_BANK
{
    /// <summary>
    /// شماره پرسنلی
    /// </summary>
    public string NUM_PRSN { get; set; }
    /// <summary>
    /// کدملی
    /// </summary>
    public string NUM_NNAL { set; get; }
    /// <summary>
    /// نوع حساب (حساب یا بن کارت)
    /// </summary>
    public string TYP_ACN { set; get; }
    /// <summary>
    /// کد بانک مثال ملی 10
    /// </summary>
    public string COD_BANK { set; get; }
    /// <summary>
    /// شماره حساب
    /// </summary>
    public string NUM_ACN { set; get; }
    /// <summary>
    /// شماره کارت
    /// </summary>
    public string NUM_CARD { set; get; }
    /// <summary>
    /// فعال؟
    /// </summary>
    public int FLG_ACT { get; set; }
}
//// 
//// This source code was auto-generated by xsd, Version=4.8.3928.0.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="S6XML070.dtd")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="S6XML070.dtd", IsNullable=false)]
//public partial class RPC_ACN_BANK {

//    private string nUM_PRSNField;

//    private string nUM_NNALField;

//    private string tYP_ACNField;

//    private string cOD_BANKField;

//    private string nUM_ACNField;

//    private string nUM_CARDField;

//    private string fLG_ACTField;

//    /// <remarks/>
//    public string NUM_PRSN {
//        get {
//            return this.nUM_PRSNField;
//        }
//        set {
//            this.nUM_PRSNField = value;
//        }
//    }

//    /// <remarks/>
//    public string NUM_NNAL {
//        get {
//            return this.nUM_NNALField;
//        }
//        set {
//            this.nUM_NNALField = value;
//        }
//    }

//    /// <remarks/>
//    public string TYP_ACN {
//        get {
//            return this.tYP_ACNField;
//        }
//        set {
//            this.tYP_ACNField = value;
//        }
//    }

//    /// <remarks/>
//    public string COD_BANK {
//        get {
//            return this.cOD_BANKField;
//        }
//        set {
//            this.cOD_BANKField = value;
//        }
//    }

//    /// <remarks/>
//    public string NUM_ACN {
//        get {
//            return this.nUM_ACNField;
//        }
//        set {
//            this.nUM_ACNField = value;
//        }
//    }

//    /// <remarks/>
//    public string NUM_CARD {
//        get {
//            return this.nUM_CARDField;
//        }
//        set {
//            this.nUM_CARDField = value;
//        }
//    }

//    /// <remarks/>
//    public string FLG_ACT {
//        get {
//            return this.fLG_ACTField;
//        }
//        set {
//            this.fLG_ACTField = value;
//        }
//    }
//}
