// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Transfer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // RequestReasonJobCategory
    public class Transfer_RequestReasonJobCategoryConfiguration : IEntityTypeConfiguration<Transfer_RequestReasonJobCategory>
    {
        public void Configure(EntityTypeBuilder<Transfer_RequestReasonJobCategory> builder)
        {
            builder.ToTable("RequestReasonJobCategory", "Transfer");
            builder.HasKey(x => x.Id).HasName("PK_RequestReasonJobCategory").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.RequestReasonId).HasColumnName(@"RequestReasonId").HasColumnType("int").IsRequired();
            builder.Property(x => x.CodeCategoryJobCategory).HasColumnName(@"CodeCategoryJobCategory").HasColumnType("nvarchar(2)").IsRequired().HasMaxLength(2);

            // Foreign keys
            builder.HasOne(a => a.Transfer_RequestReason).WithMany(b => b.Transfer_RequestReasonJobCategories).HasForeignKey(c => c.RequestReasonId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_RequestReasonJobCategory_RequestReason");
        }
    }

}
// </auto-generated>
