// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.ODSViews
{
    // View_ODS_TherapyBooklet_MIS
    public class ViewOdsTherapyBookletMis : IEntityBase
    {
        public decimal? IsnNum { get; set; } // ISN_NUM
        public decimal? NumNnalThbkt { get; set; } // NUM_NNAL_THBKT
        public decimal? NumPrsnThbkt { get; set; } // NUM_PRSN_THBKT
        public string NamThbkt { get; set; } // NAM_THBKT (length: 20)
        public string NamFamThbkt { get; set; } // NAM_FAM_THBKT (length: 25)
        public decimal? CodSexThbkt { get; set; } // COD_SEX_THBKT
        public decimal? NumCrtThbkt { get; set; } // NUM_CRT_THBKT
        public decimal? DatBrtThbkt { get; set; } // DAT_BRT_THBKT
        public decimal? CodDpncyThbkt { get; set; } // COD_DPNCY_THBKT
        public string NamFthrThbkt { get; set; } // NAM_FTHR_THBKT (length: 20)
        public string NumBookThbkt { get; set; } // NUM_BOOK_THBKT (length: 12)
        public decimal? NumStrBookThbkt { get; set; } // NUM_STR_BOOK_THBKT
        public decimal? NumEndBookThbkt { get; set; } // NUM_END_BOOK_THBKT
        public decimal? DatEndBookThbkt { get; set; } // DAT_END_BOOK_THBKT
        public decimal? FlgExmptThbkt { get; set; } // FLG_EXMPT_THBKT
        public decimal? CodStaThbkt { get; set; } // COD_STA_THBKT
        public decimal? NumLevThbkt { get; set; } // NUM_LEV_THBKT
        public string TypFrchThbkt { get; set; } // TYP_FRCH_THBKT (length: 15)
        public decimal? PcnFrchThbkt { get; set; } // PCN_FRCH_THBKT
        public decimal? DatStrDpncyThbkt { get; set; } // DAT_STR_DPNCY_THBKT
        public decimal? DatEndDpncyThbkt { get; set; } // DAT_END_DPNCY_THBKT
        public decimal? CodEndThbkt { get; set; } // COD_END_THBKT
        public decimal? DatUpdThbkt { get; set; } // DAT_UPD_THBKT
        public string CodUsrThbkt { get; set; } // COD_USR_THBKT (length: 8)
        public decimal? FlgStaBookThbkt { get; set; } // FLG_STA_BOOK_THBKT
        public string NumAcnBnkThbkt { get; set; } // NUM_ACN_BNK_THBKT (length: 25)
        public decimal? CodCityThbkt { get; set; } // COD_CITY_THBKT
        public string FkBktyp { get; set; } // FK_BKTYP (length: 2)
        public string CodBnkPensnThbkt { get; set; } // COD_BNK_PENSN_THBKT (length: 2)
        public string CodRngCityThbkt { get; set; } // COD_RNG_CITY_THBKT (length: 2)
        public string CodCntryCityThbkt { get; set; } // COD_CNTRY_CITY_THBKT (length: 3)
        public decimal? Expr1 { get; set; } // Expr1
        public decimal? Expr2 { get; set; } // Expr2
        public decimal? NumCntrPensnThbkt { get; set; } // NUM_CNTR_PENSN_THBKT
        public bool? HisFlgOdsdb { get; set; } // HIS_FLG_ODSDB
    }
}


 
