// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.ODSViews
{
    // View_MIS_SalaryCode
    public class ViewMisUserDefinition : IEntityBase
    {

        public long Id { get; set; } // Id
        public string MisUser { get; set; } // MisUser (length: 8)
        public decimal? PersonalNumber { get; set; } // PersonalNumber
        public string WinUser { get; set; } // WinUser (length: 20)
        public string NationalCode { get; set; } // NationalCode (length: 15)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)

    }

}
// </auto-generated>
