// <auto-generated>
// ReSharper disable All

using KSC.Domain;

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.ODSViews
{
    // View_MIS_JobCategory
    public class ViewMisJobCategory : IEntityBase
    {
        public decimal JobCategoryCode { get; set; } // JobCategoryCode
        public string JobCategoryTitle { get; set; } // JobCategoryTitle (length: 30)
        public string CodeCategoryJobCategory { get; set; } // CodeCategoryJobCategory (length: 2)
    }

}
// </auto-generated>
