// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.Hr.Domain.Entities
{
    // View_EmployeeWithFamilyActive
    public class ViewEmployeeWithFamilyActive : IEntityBase
    {
        public string EmployeeNumber { get; set; } // EmployeeNumber (length: 50)
        public string FirstName { get; set; } // FirstName (length: 500)
        public string LastName { get; set; } // LastName (length: 500)
        public int EmployeeId { get; set; } // EmployeeId
        public int? FamilyId { get; set; } // FamilyId
        public string NationalCode { get; set; } // NationalCode (length: 50)
        public int DependenceTypeId { get; set; } // DependenceTypeId
        public string DependenceTypeTitle { get; set; } // DependenceTypeTitle
        public bool? IsContinuesDependent { get; set; } // IsContinuesDependent
        public DateTime? StartDateDependent { get; set; } // StartDateDependent
        public DateTime? EndDateDependent { get; set; } // EndDateDependent
        public DateTime? BirthDate { get; set; } // BirthDate
        public int? GenderId { get; set; } // GenderId
        public string GenderTitle { get; set; } // GenderTitle (length: 50)
    }

}
// </auto-generated>
