// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.BusinessTrip
{
    // Location
    /// <summary>
    /// مکان ماموریت
    /// </summary>
    public class Mission_Location : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// مکان ماموریت
        /// </summary>
        public string Title { get; set; } // Title (length: 50)
        /// <summary>
        /// حداکثر تعداد روزهای ماموریت برای پرداخت
        /// </summary>
        public int? MaximumMissionDayForPayment { get; set; } // MaximumMissionDayForPayment

        // Reverse navigation

        /// <summary>
        /// Child Mission_Requests where [Request].[MissionLocationId] point to this entity (FK_Request_Location)
        /// </summary>
        public virtual ICollection<Mission_Request> Mission_Requests { get; set; } // Request.FK_Request_Location
        /// <summary>
        /// Child Mission_TypeLocations where [TypeLocation].[MissionLocationId] point to this entity (FK_TypeLocation_Location)
        /// </summary>
        public virtual ICollection<Mission_TypeLocation> Mission_TypeLocations { get; set; } // TypeLocation.FK_TypeLocation_Location
        public Mission_Location()
        {
            Mission_Requests = new List<Mission_Request>();
            Mission_TypeLocations = new List<Mission_TypeLocation>();
        }
    }

}
// </auto-generated>
