// <auto-generated>
// ReSharper disable All
using Ksc.HR.Domain.Entities.WorkFlow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // JobCategoryRange
    public class WF_JobCategoryRangeConfiguration : IEntityTypeConfiguration<WF_JobCategoryRange>
    {
        public void Configure(EntityTypeBuilder<WF_JobCategoryRange> builder)
        {
            builder.ToTable("JobCategoryRange", "WF");
            builder.HasKey(x => x.Id).HasName("PK_WF_JobCategoryRange").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.WorkFlowProcessId).HasColumnName(@"WorkFlowProcessId").HasColumnType("int").IsRequired();
            builder.Property(x => x.LowestJobCategoryCode).HasColumnName(@"LowestJobCategoryCode").HasColumnType("nvarchar(2)").IsRequired().HasMaxLength(2);
            builder.Property(x => x.HighestJobCategoryCode).HasColumnName(@"HighestJobCategoryCode").HasColumnType("nvarchar(2)").IsRequired().HasMaxLength(2);

            // Foreign keys
            builder.HasOne(a => a.WF_Process).WithMany(b => b.WF_JobCategoryRanges).HasForeignKey(c => c.WorkFlowProcessId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_JobCategoryRange_Process");
        }
    }

}
// </auto-generated>
