// <auto-generated>
// ReSharper disable All
using Ksc.HR.Domain.Entities.WorkFlow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // WorkFlowStatusReason
    public class WF_WorkFlowStatusReasonConfiguration : IEntityTypeConfiguration<WF_WorkFlowStatusReason>
    {
        public void Configure(EntityTypeBuilder<WF_WorkFlowStatusReason> builder)
        {
            builder.ToTable("WorkFlowStatusReason", "WF");
            builder.HasKey(x => x.Id).HasName("PK_WF_WorkFlowStatusReason").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.WorkFlowManagementId).HasColumnName(@"WorkFlowManagementId").HasColumnType("int").IsRequired();
            builder.Property(x => x.StatusReasonId).HasColumnName(@"StatusReasonId").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.WF_StatusReason).WithMany(b => b.WF_WorkFlowStatusReasons).HasForeignKey(c => c.StatusReasonId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_WF_WorkFlowStatusReason_WF_StatusReason");
            builder.HasOne(a => a.WF_WorkFlowManagement).WithMany(b => b.WF_WorkFlowStatusReasons).HasForeignKey(c => c.WorkFlowManagementId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_WF_WorkFlowStatusReason_WF_WorkFlowManagement");
        }
    }

}
// </auto-generated>
