// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using KSC.Domain;
using Ksc.HR.Domain.Entities.Workshift;

namespace Ksc.HR.Domain.Entities.Personal
{
    // EmployeeSafetyDeduction
    /// <summary>
    /// ساعات آموزشی افراد
    /// </summary>
    public class EmployeeSafetyDeduction : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int? EmployeeId { get; set; } // EmployeeId
        //public string EmployeeNumber { get; set; } // EmployeeNumber (length: 50)
        public int YearMonth { get; set; }
        public int SumNegativeScore { get; set; }
        public int SumPercent { get; set; }
        public int ActionId { get; set; }
        public DateTime? CreateDateTime { get; set; } // CreateDateTime
        public string CreateUser { get; set; } // CreateUser (length: 50)
 
        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [EmployeeSafetyDeduction].([EmployeeId]) (FK_EmployeeSafetyDeduction_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeSafetyDeduction_Employee


    }

}
// </auto-generated>
