// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using KSC.Domain;
using Ksc.HR.Domain.Entities.Workshift;

namespace Ksc.HR.Domain.Entities.Personal
{
    // EmployeeEfficiencyHistory
    /// <summary>
    /// تاریخچه ضریب کارایی افراد
    /// </summary>
    public class EmployeeEfficiencyHistory : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmployeeId { get; set; } // EmployeeId
        public int YearMonth { get; set; } // YearMonth
        public decimal Efficiency { get; set; } // Efficiency
        public bool IsLatest { get; set; } // IsLatest
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)

        public string RemoteIpAddress { get; set; } // RemoteIpAddress (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [EmployeeEfficiencyHistory].([EmployeeId]) (FK_EmployeeEfficiencyHistory_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeEfficiencyHistory_Employee

    }

}
// </auto-generated>
