// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using KSC.Domain;
using Ksc.HR.Domain.Entities.WorkFlow;
using Ksc.HR.Domain.Entities.Workshift;

namespace Ksc.HR.Domain.Entities.Personal
{
    // EmployeeLongTermAbsence
    /// <summary>
    /// عدم حضور طولانی مدت
    /// </summary>
    public class EmployeeLongTermAbsence : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmployeeId { get; set; } // EmployeeId

        /// <summary>
        /// تاریخ شروع
        /// </summary>
        public DateTime AbsenceStartDate { get; set; } // AbsenceStartDate

        /// <summary>
        /// تاریخ پایان
        /// </summary>
        public DateTime AbsenceEndDate { get; set; } // AbsenceEndDate

        /// <summary>
        /// تعدا روزهای غیبت
        /// </summary>
        public int AbsenceDayCount { get; set; } // AbsenceDayCount

        /// <summary>
        /// کد حضور غیاب
        /// </summary>
        /// 
        public int RollCallDefinitionId { get; set; } // RollCallDefinitionId

        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        public bool IsDeleted { get; set; }


        // Foreign keys

        public ICollection<EmployeeAttendAbsenceItem>  EmployeeAttendAbsenceItems { get; set; }
        /// <summary>
        /// Parent Employee pointed by [EmployeeLongTermAbsence].([EmployeeId]) (FK_EmployeeLongTermAbsence_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeLongTermAbsence_Employee

        /// <summary>
        /// Parent RollCallDefinition pointed by [EmployeeLongTermAbsence].([RollCallDefinitionId]) (FK_EmployeeLongTermAbsence_RollCallDefinition)
        /// </summary>
        public virtual RollCallDefinition RollCallDefinition { get; set; } // FK_EmployeeLongTermAbsence_RollCallDefinition
    }

}
// </auto-generated>
