// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Workshift;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Personal
{
    // MonthTimeSheetDraft
    /// <summary>
    /// پیشنویس تایم-شیت ماهیانه
    /// </summary>
    public class MonthTimeSheetDraft : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// شناسه پرسنلی
        /// </summary>
        public int EmployeeId { get; set; } // EmployeeId

        /// <summary>
        /// سال-ماه
        /// </summary>
        public int YearMonth { get; set; } // YearMonth
        public int WorkTimeId { get; set; } // WorkTimeId

        /// <summary>
        /// اضافه کار قهری
        /// </summary>
        public int ForcedOverTime { get; set; } // ForcedOverTime 

        /// <summary>
        /// تعداد روزها
        /// </summary>
        public int? DayCount { get; set; } // DayCount

        /// <summary>
        /// مزایای حق شیفت
        /// </summary>
        public int? ShiftBenefitDayCount { get; set; } // ShiftBenefitDayCount
        public int? LastForcedOverTime { get; set; } // LastForcedOverTime

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [MonthTimeSheetDraft].([EmployeeId]) (FK_MonthTimeSheetDraft_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_MonthTimeSheetDraft_Employee

        /// <summary>
        /// Parent WorkTime pointed by [MonthTimeSheetDraft].([WorkTimeId]) (FK_MonthTimeSheetDraft_WorkTime)
        /// </summary>
        public virtual WorkTime WorkTime { get; set; } // FK_MonthTimeSheetDraft_WorkTime
    }

}
// </auto-generated>
