// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Salary
{
    // AccountCodeMarital
    public class AccountCodeMarital:IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// کد حساب
        /// </summary>
        public int AccountCodeId { get; set; } // AccountCodeId

        /// <summary>
        /// وضعیت تاهل
        /// </summary>
        public int MaritalStatusId { get; set; } // MaritalStatusId

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool? IsActive { get; set; } // IsActive

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        // Foreign keys

        /// <summary>
        /// Parent MaritalStatu pointed by [AccountCodeMarital].([MaritalStatusId]) (FK_AccountCodeMarital_MaritalStatus)
        /// </summary>
        public virtual MaritalStatus MaritalStatus { get; set; } // FK_AccountCodeMarital_MaritalStatus

        /// <summary>
        /// Parent Salary_AccountCode pointed by [AccountCodeMarital].([AccountCodeId]) (FK_AccountCodeMarital_AccountCode)
        /// </summary>
        public virtual AccountCode AccountCode { get; set; } // FK_AccountCodeMarital_AccountCode
    }

}
// </auto-generated>
