// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using ChefHesab.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChefHesab.Data.Configurations
{
    public partial class ContractingCompanyConfiguration : IEntityTypeConfiguration<ContractingCompany>
    {
        public void Configure(EntityTypeBuilder<ContractingCompany> entity)
        {
            entity.HasComment("شرکت های تحت قرار داد کاربران");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Personal)
                .WithMany(p => p.ContractingCompanies)
                .HasForeignKey(d => d.PersonalId)
                .HasConstraintName("FK_ContractingCompanies_Personal");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContractingCompany> entity);
    }
}
