// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Rule;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.Hr.Data.Persistant.Configurations
{
    // EmployeeDisConnection
    public class EmployeeDisConnectionConfiguration : IEntityTypeConfiguration<EmployeeDisConnection>
    {
        public void Configure(EntityTypeBuilder<EmployeeDisConnection> builder)
        {
            builder.ToTable("EmployeeDisConnection", "Rule");
            builder.HasKey(x => x.Id).HasName("PK_DisConnection").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Duration).HasColumnName(@"Duration").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DisConnectionTypeId).HasColumnName(@"DisConnectionTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.EmployeeDisConnections).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeDisConnection_Employee");
            builder.HasOne(a => a.DisConnectionType).WithMany(b => b.EmployeeDisConnections).HasForeignKey(c => c.DisConnectionTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeDisConnection_DisConnectionType");
        }
    }

}
// </auto-generated>
