// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Rule;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // InterdictType
    public class InterdictTypeConfiguration : IEntityTypeConfiguration<InterdictType>
    {
        public void Configure(EntityTypeBuilder<InterdictType> builder)
        {
            builder.ToTable("InterdictType", "Rule");
            builder.HasKey(x => x.Id).HasName("PK_RuleType").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsEditableJobGroup).HasColumnName(@"IsEditableJobGroup").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsEditableJobPosition).HasColumnName(@"IsEditableJobPosition").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsRemovableFlag).HasColumnName(@"IsRemovableFlag").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
