// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Oncall;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // Type
    public class OnCall_TypeConfiguration : IEntityTypeConfiguration<OnCall_Type>
    {
        public void Configure(EntityTypeBuilder<OnCall_Type> builder)
        {
            builder.ToTable("Type", "OnCall");
            builder.HasKey(x => x.Id).HasName("PK_OncallType").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(200)").IsRequired().HasMaxLength(200);
            builder.Property(x => x.RollCallDefinitionId).HasColumnName(@"RollCallDefinitionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.OnlyCurrentDay).HasColumnName(@"OnlyCurrentDay").HasColumnType("bit").IsRequired();
            builder.Property(x => x.MinimumDayCount).HasColumnName(@"MinimumDayCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MaximumDayCount).HasColumnName(@"MaximumDayCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            builder.HasOne(a => a.RollCallDefinition).WithMany(b => b.OnCall_Types).HasForeignKey(c => c.RollCallDefinitionId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_OnCallType_RollCallDefinition");
        }
    }

}
// </auto-generated>
