// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Oncall;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // AcessManagmentOnCallType
    public class OnCall_AcessManagmentOnCallTypeConfiguration : IEntityTypeConfiguration<OnCall_AcessManagmentOnCallType>
    {
        public void Configure(EntityTypeBuilder<OnCall_AcessManagmentOnCallType> builder)
        {
            builder.ToTable("AcessManagmentOnCallType", "OnCall");
            builder.HasKey(x => x.Id).HasName("PK_AcessManagmentOnCallType").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.OnCallTypeId).HasColumnName(@"OnCallTypeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DomainName).HasColumnName(@"DomainName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            builder.HasOne(a => a.OnCall_Type).WithMany(b => b.OnCall_AcessManagmentOnCallTypes).HasForeignKey(c => c.OnCallTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AcessManagmentOnCallType_Type");
        }
    }

}
// </auto-generated>
