// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Oncall;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // View_OnCallRequest
    public class ViewOnCallRequestConfiguration : IEntityTypeConfiguration<ViewOnCallRequest>
    {
        public void Configure(EntityTypeBuilder<ViewOnCallRequest> builder)
        {
            builder.ToView("View_OnCallRequest", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.OnCallTypeId).HasColumnName(@"OnCallTypeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsRequired();
            builder.Property(x => x.JobPositionCode).HasColumnName(@"JobPositionCode").HasColumnType("nvarchar(13)").IsRequired().HasMaxLength(13);
            builder.Property(x => x.WorkTimeId).HasColumnName(@"WorkTimeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.OnCallDate).HasColumnName(@"OnCallDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.OnCallReason).HasColumnName(@"OnCallReason").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.CallingCostCenter).HasColumnName(@"CallingCostCenter").HasColumnType("numeric(6,0)").HasPrecision(6,0).IsRequired();
            builder.Property(x => x.CallingSubFunctionCode).HasColumnName(@"CallingSubFunctionCode").HasColumnType("numeric(4,0)").HasPrecision(4,0).IsRequired();
            builder.Property(x => x.OnCallStartDate).HasColumnName(@"OnCallStartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.OnCallStartTime).HasColumnName(@"OnCallStartTime").HasColumnType("char(5)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.OnCallEndDate).HasColumnName(@"OnCallEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.OnCallEndTime).HasColumnName(@"OnCallEndTime").HasColumnType("char(5)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.OnCallStartDateTime).HasColumnName(@"OnCallStartDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.OnCallEndtDateTime).HasColumnName(@"OnCallEndtDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.DurationAsMinute).HasColumnName(@"DurationAsMinute").HasColumnType("int").IsRequired(false);
        }
    }

}
// </auto-generated>
