// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.BusinessTrip;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations.BusinessTrip
{
    // Type
    public class Mission_TypeConfiguration : IEntityTypeConfiguration<Mission_Type>
    {
        public void Configure(EntityTypeBuilder<Mission_Type> builder)
        {
            builder.ToTable("Type", "Mission");
            builder.HasKey(x => x.Id).HasName("PK_Type_1").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.OutsideProviceMinimumDay).HasColumnName(@"OutsideProviceMinimumDay").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
