// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.EmployeeBase;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // BasisSalaryItem
    /// <summary>
    /// جدول مبنا پرداخت حقوق
    /// </summary>
    public class BasisSalaryItem : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// نوع استخدام
        /// </summary>
        public int EmploymentTypeId { get; set; } // EmploymentTypeId

        /// <summary>
        /// تاریخ اعتبار از
        /// </summary>
        public int StartDate { get; set; } // StartDate

        /// <summary>
        /// تاریخ اعتبار تا
        /// </summary>
        public int EndDate { get; set; } // EndDate

        /// <summary>
        /// حداقل مزد روزانه
        /// </summary>
        public long MinDailySalaryAmount { get; set; } // MinDailySalaryAmount

        /// <summary>
        /// ضریب جدول
        /// </summary>
        public double TableCoefficient { get; set; } // TableCoefficient

        /// <summary>
        /// فعال؟
        /// </summary>
        //public bool IsActive { get; set; } // IsActive

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsConfirmed { get; set; } // IsConfirmed
        public bool IsActive { get; set; }
        public virtual EmploymentType EmploymentType { get; set; } // FK_AccountCodeEmploymentType_EmploymentType

        // Reverse navigation

        /// <summary>
        /// Child BasisSalaryItemPerGroups where [BasisSalaryItemPerGroup].[BasisSalaryItemId] point to this entity (FK_BasisSalaryItemPerGroup_BasisSalaryItem)
        /// </summary>
        public virtual ICollection<BasisSalaryItemPerGroup> BasisSalaryItemPerGroups { get; set; } // BasisSalaryItemPerGroup.FK_BasisSalaryItemPerGroup_BasisSalaryItem

        public BasisSalaryItem()
        {
            BasisSalaryItemPerGroups = new List<BasisSalaryItemPerGroup>();
        }
    }

}
// </auto-generated>
