// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // Coefficient
    /// <summary>
    /// عناوین ضریب
    /// </summary>
    public class Coefficient : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان ضریب
        /// </summary>
        public string Title { get; set; } // Title (length: 500)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool? IsActive { get; set; } // IsActive

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child CoefficientSettings where [CoefficientSetting].[CoefficientId] point to this entity (FK_CoefficientSetting_Coefficient)
        /// </summary>
        public virtual ICollection<CoefficientSetting> CoefficientSettings { get; set; } // CoefficientSetting.FK_CoefficientSetting_Coefficient

        public Coefficient()
        {
            CoefficientSettings = new List<CoefficientSetting>();
        }
    }

}
// </auto-generated>
