// <auto-generated>
// ReSharper disable All

using DNTPersianUtils.Core;
using Ksc.HR.Domain.Entities.Chart;
using Ksc.HR.Domain.Entities.Emp;
using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.WorkFlow;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // EmployeePromotion
    /// <summary>
    /// ارتقا گروه
    /// </summary>
    public class EmployeePromotion : IEntityBase<int>
    {
        public EmployeePromotion()
        {
            EmployeePromotionInterdicts = new List<EmployeePromotionInterdicts>();

        }
        public int Id { get; set; } // Id (Primary key)

        ///// <summary>
        ///// آخرین حکم مورد محاسبه
        ///// </summary>
        //public int? LastInterdictId { get; set; }
        /// <summary>
        /// شناسه پرسنل
        /// </summary>
        public int? EmployeeId { get; set; } // EmployeeId

        /// <summary>
        /// تاریخ محاسبه
        /// </summary>
        public int? CalculateDate { get; set; } // CalculateDate

        /// <summary>
        /// سابقه کل
        /// </summary>
        public int? TotalHistory { get; set; } // TotalHistory

        /// <summary>
        /// ضریب عملکرد
        /// </summary>
        public double? PerformanceRate { get; set; } // PerformanceRate

        /// <summary>
        /// امتیاز آموزشی
        /// </summary>
        //public float? TrainingScore { get; set; } // TrainingScore
        public double? TrainingScore { get; set; } // TrainingScore

        /// <summary>
        /// گروه شغل جاری
        /// </summary>
        public int? CurrentJobGroupId { get; set; } // CurrentJobGroupId

        /// <summary>
        /// گروه شغل جدید
        /// </summary>
        public int? NewJobGroupId { get; set; } // NewJobGroupId

        /// <summary>
        /// کد پست
        /// </summary>
        public int? JobPositionId { get; set; } // JobPositionId

        /// <summary>
        /// مدرک تحصیلی فرد
        /// </summary>
        public int? EmployeeEducationDegreeId { get; set; } // EmployeeEducationDegreeId

        /// <summary>
        /// مدرک تحصیلی پست
        /// </summary>
        //public int? JobPositionFieldId { get; set; } // JobPositionFieldId

        /// <summary>
        /// ضریب تعدیل مدرک
        /// </summary>
        public double? DegreeBalanceRate { get; set; } // DegreeBalanceRate

        /// <summary>
        /// وضعیت ارتقا
        /// </summary>
        public int? PromotionStatusId { get; set; } // PromotionStatusId
        public DateTime? PromotionDate { get; set; } // PromotionDate


        public int? PromotionDateYearMonth { get; set; }
        /// <summary>
        /// ساعت آموزش
        /// </summary>
        public int? TrainingHour { get; set; } // TrainingHour

        /// <summary>
        /// امتیاز بهپویی
        /// </summary>
        public int? KizenScore { get; set; } // KizenScore

        /// <summary>
        /// دلیل رد ارتقا
        /// </summary>
        public int? PromotionRejectReasonId { get; set; } // PromotionRejectReasonId

        /// <summary>
        /// شناسه درخواست
        /// </summary>
        public int? WfRequestId { get; set; } // WFRequestId

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Chart_JobGroup pointed by [EmployeePromotion].([CurrentJobGroupId]) (FK_EmployeePromotion_JobGroupCurrent)
        /// </summary>
        public virtual JobGroup CurrentJobGroup { get; set; } // FK_EmployeePromotion_JobGroupCurrent

        /// <summary>
        /// Parent Chart_JobGroup pointed by [EmployeePromotion].([NewJobGroupId]) (FK_EmployeePromotion_JobGroupNew)
        /// </summary>
        public virtual JobGroup NewJobGroup { get; set; } // FK_EmployeePromotion_JobGroupNew

        /// <summary>
        /// Parent Chart_JobPosition pointed by [EmployeePromotion].([JobPositionId]) (FK_EmployeePromotion_JobPosition)
        /// </summary>
        public virtual Chart_JobPosition Chart_JobPosition { get; set; } // FK_EmployeePromotion_JobPosition

        /// <summary>
        /// Parent Chart_JobPositionField pointed by [EmployeePromotion].([JobPositionFieldId]) (FK_EmployeePromotion_JobPositionField)
        /// </summary>
        //public virtual Chart_JobPositionField Chart_JobPositionField { get; set; } // FK_EmployeePromotion_JobPositionField

        /// <summary>
        /// Parent EmployeeEducationDegree pointed by [EmployeePromotion].([EmployeeEducationDegreeId]) (FK_EmployeePromotion_EmployeeEducationDegree)
        /// </summary>
        public virtual EmployeeEducationDegree EmployeeEducationDegree { get; set; } // FK_EmployeePromotion_EmployeeEducationDegree

        /// <summary>
        /// Parent Employee pointed by [EmployeePromotion].([EmployeeId]) (FK_EmployeePromotion_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeePromotion_Employee

        /// <summary>
        /// Parent PromotionRejectReason pointed by [EmployeePromotion].([PromotionRejectReasonId]) (FK_EmployeePromotion_PromotionRejectReason)
        /// </summary>
        public virtual PromotionRejectReason PromotionRejectReason { get; set; } // FK_EmployeePromotion_PromotionRejectReason

        /// <summary>
        /// Parent PromotionStatus pointed by [EmployeePromotion].([PromotionStatusId]) (FK_EmployeePromotion_PromotionStatus)
        /// </summary>
        public virtual PromotionStatus PromotionStatus { get; set; } // FK_EmployeePromotion_PromotionStatus

        /// <summary>
        /// Parent WF_Request pointed by [EmployeePromotion].([WfRequestId]) (FK_EmployeePromotion_Request)
        /// </summary>
        public virtual WF_Request WF_Request { get; set; } // FK_EmployeePromotion_Request

        public virtual IEnumerable<EmployeePromotionInterdicts> EmployeePromotionInterdicts { get; set; }
    }

}
// </auto-generated>
