// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // EmployeeInterdictDetail
    public class EmployeeInterdictDetail : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// شناسه جدول حکم
        /// </summary>
        public int EmployeeInterdictId { get; set; } // EmployeeInterdictId

        /// <summary>
        /// کد حساب
        /// </summary>
        public int AccountCodeId { get; set; } // AccountCodeId

        /// <summary>
        /// مبلغ
        /// </summary>
        public long Amount { get; set; } // Amount

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Rule_EmployeeInterdict pointed by [EmployeeInterdictDetail].([EmployeeInterdictId]) (FK_EmployeeInterdictDetail_EmployeeInterdict)
        /// </summary>
        public virtual EmployeeInterdict EmployeeInterdict { get; set; } // FK_EmployeeInterdictDetail_EmployeeInterdict

        /// <summary>
        /// Parent Salary_AccountCode pointed by [EmployeeInterdictDetail].([AccountCodeId]) (FK_EmployeeInterdictDetail_AccountCode)
        /// </summary>
        public virtual AccountCode AccountCode { get; set; } // FK_EmployeeInterdictDetail_AccountCode

        public EmployeeInterdictDetail()
        {
            IsActive = true;
        }
    }

}
// </auto-generated>
