// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // IncreaseSalaryHeader
    public class IncreaseSalaryHeader : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// سال
        /// </summary>
        public int Year { get; set; } // Year

        /// <summary>
        /// تاریخ شروع اعتبار
        /// </summary>
        public int ValidStartDate { get; set; } // ValidStartDate

        /// <summary>
        /// تاریخ پایان اعتبار
        /// </summary>
        public int ValidEndDate { get; set; } // ValidEndDate

        /// <summary>
        /// از تاریخ مبنا محاسبه
        /// </summary>
        public DateTime CalculateStartDate { get; set; } // CalculateStartDate

        /// <summary>
        /// تا تاریخ مبنا محاسبه
        /// </summary>
        public DateTime CalculateEndDate { get; set; } // CalculateEndDate

        /// <summary>
        /// درصد افزایش
        /// </summary>
        public decimal IncreasePercent { get; set; } // IncreasePercent

        /// <summary>
        /// تاریخ اجرا
        /// </summary>
        public DateTime ExecuteDate { get; set; } // ExecuteDate

        /// <summary>
        /// نوع حکم
        /// </summary>
        public int InterdictTypeId { get; set; } // InterdictTypeId

        /// <summary>
        /// تاریخ مبنا تحت تکفل
        /// </summary>
        public DateTime BaseDateforMarital { get; set; } // BaseDateforMarital

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsFinal { get; set; } // IsFinal

        // Reverse navigation

        /// <summary>
        /// Child Rule_IncreaseSalaryDetails where [IncreaseSalaryDetail].[IncreasedSalaryHeaderId] point to this entity (FK_IncreaseSalaryDetail_IncreaseSalaryHeader)
        /// </summary>
        public virtual ICollection<IncreaseSalaryDetail> IncreaseSalaryDetails { get; set; } // IncreaseSalaryDetail.FK_IncreaseSalaryDetail_IncreaseSalaryHeader

        // Foreign keys

        /// <summary>
        /// Parent Rule_InterdictType pointed by [IncreaseSalaryHeader].([InterdictTypeId]) (FK_IncreaseSalaryHeader_InterdictType)
        /// </summary>
        public virtual InterdictType Rule_InterdictType { get; set; } // FK_IncreaseSalaryHeader_InterdictType

        public IncreaseSalaryHeader()
        {
            IncreaseSalaryDetails = new List<IncreaseSalaryDetail>();
        }
    }

}
// </auto-generated>
