// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // InterdictMaritalSettingDetail
    public class InterdictMaritalSettingDetail : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عائله مندی
        /// </summary>
        public int InterdictMaritalSettingId { get; set; } // InterdictMaritalSettingId

        /// <summary>
        /// کد حساب
        /// </summary>
        public int AccountCodeId { get; set; } // AccountCodeId

        /// <summary>
        /// وضعیت تاهل
        /// </summary>
        public int? MaritalStatusId { get; set; } // MaritalStatusId

        /// <summary>
        /// مبلغ
        /// </summary>
        public long? Amount { get; set; } // Amount

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool? IsActive { get; set; } // IsActive

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent MaritalStatu pointed by [InterdictMaritalSettingDetail].([MaritalStatusId]) (FK_InterdictMaritalSettingDetail_MaritalStatus)
        /// </summary>
        public virtual MaritalStatus MaritalStatus { get; set; } // FK_InterdictMaritalSettingDetail_MaritalStatus

        /// <summary>
        /// Parent Rule_InterdictMaritalSetting pointed by [InterdictMaritalSettingDetail].([InterdictMaritalSettingId]) (FK_InterdictMaritalSettingDetail_InterdictMaritalSetting)
        /// </summary>
        public virtual InterdictMaritalSetting InterdictMaritalSetting { get; set; } // FK_InterdictMaritalSettingDetail_InterdictMaritalSetting

        /// <summary>
        /// Parent Salary_AccountCode pointed by [InterdictMaritalSettingDetail].([AccountCodeId]) (FK_InterdictMaritalSettingDetail_AccountCode)
        /// </summary>
        public virtual AccountCode AccountCode { get; set; } // FK_InterdictMaritalSettingDetail_AccountCode
    }

}
// </auto-generated>
