// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Rule
{
    // InterdictStatus
    public class InterdictStatus : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 200)
        public bool IsActive { get; set; } // IsActive
        public DateTime? InsertDate { get; set; } // InsertDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child EmployeeInterdicts where [EmployeeInterdict].[InterdictStatusId] point to this entity (FK_EmployeeInterdict_InterdictStatus)
        /// </summary>
        public virtual ICollection<EmployeeInterdict> EmployeeInterdicts { get; set; } // EmployeeInterdict.FK_EmployeeInterdict_InterdictStatus

        public InterdictStatus()
        {
            EmployeeInterdicts = new List<EmployeeInterdict>();
        }
    }

}
// </auto-generated>
