// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.EmployeeBase;
using Ksc.HR.Domain.Entities.Workshift;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Emp
{
    // ConditionalAbsenceType
    public class ConditionalAbsenceType : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 500)

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        /// <summary>
        /// قابل استفاده در ابتدای شیفت؟
        /// </summary>
        public bool IsInStartShift { get; set; } // IsInStartShift

        /// <summary>
        /// عدم حضور ساعتی است؟
        /// </summary>
        public bool IsHourlyAbsence { get; set; } // IsHourlyAbsence

        // Reverse navigation

        /// <summary>
        /// Child EmployeeBase_ConditionalAbsenceSubjectTypes where [ConditionalAbsenceSubjectType].[ConditionalAbsenceTypeId] point to this entity (FK_ConditionalAbsenceSubjectType_ConditionalAbsenceType)
        /// </summary>
        public virtual ICollection<ConditionalAbsenceSubjectType> ConditionalAbsenceSubjectTypes { get; set; } // ConditionalAbsenceSubjectType.FK_ConditionalAbsenceSubjectType_ConditionalAbsenceType

        public ConditionalAbsenceType()
        {
            ConditionalAbsenceSubjectTypes = new List<ConditionalAbsenceSubjectType>();
        }
    }

}
// </auto-generated>
