// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.EmployeeBase

{
    // InsuranceList
    public class InsuranceList : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 50)

        /// <summary>
        /// نوع بیمه
        /// </summary>
        public int InsuranceTypeId { get; set; } // InsuranceTypeId

        /// <summary>
        /// کد کارگاه
        /// </summary>
        public string WorkShopCode { get; set; } // WorkShopCode (length: 50)

        /// <summary>
        /// آدرس
        /// </summary>
        public string Address { get; set; } // Address

        /// <summary>
        /// ردیف پیمان
        /// </summary>
        public string AgreementRow { get; set; } // AgreementRow (length: 50)

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive
        /// <summary>
        /// Child Employees where [Employee].[InsuranceListId] point to this entity (FK_Employee_InsuranceList)
        /// </summary>
        public virtual ICollection<Employee> Employees { get; set; } // Employee.FK_Employee_InsuranceList
        // Foreign keys

        /// <summary>
        /// Parent EmployeeBase_InsuranceType pointed by [InsuranceList].([InsuranceTypeId]) (FK_InsuranceList_InsuranceType)
        /// </summary>
        public virtual InsuranceType InsuranceType { get; set; } // FK_InsuranceList_InsuranceType
        public InsuranceList()
        {
            Employees = new List<Employee>();
        }
    }

}
// </auto-generated>
