// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using KSC.Domain;

namespace Ksc.HR.Domain.Entities.EmployeeBase
{
    // InsuranceType
    public class InsuranceType : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title (length: 50)

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربردرج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child AnnualInsurances where [AnnualInsurance].[InsuranceTypeId] point to this entity (FK_AnnualInsurance_InsuranceType)
        /// </summary>
       // public virtual ICollection<AnnualInsurance> AnnualInsurances { get; set; } // AnnualInsurance.FK_AnnualInsurance_InsuranceType

        /// <summary>
        /// Child Employees where [Employee].[InsuranceTypeId] point to this entity (FK_Employee_InsuranceType)
        /// </summary>
     //   public virtual ICollection<Employee> Employees { get; set; } // Employee.FK_Employee_InsuranceType

        /// <summary>
        /// Child InsuranceLists where [InsuranceList].[InsuranceTypeId] point to this entity (FK_InsuranceList_InsuranceType)
        /// </summary>
        public virtual ICollection<InsuranceList> InsuranceLists { get; set; } // InsuranceList.FK_InsuranceList_InsuranceType

        public InsuranceType()
        {
            //AnnualInsurances = new List<AnnualInsurance>();
          //  Employees = new List<Employee>();
            InsuranceLists = new List<InsuranceList>();
        }
    }

}
// </auto-generated>
