// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // AnalysisEmployeeAttendAbsenceItem
    public class AnalysisEmployeeAttendAbsenceItemConfiguration : IEntityTypeConfiguration<AnalysisEmployeeAttendAbsenceItem>
    {
        public void Configure(EntityTypeBuilder<AnalysisEmployeeAttendAbsenceItem> builder)
        {
            builder.ToTable("AnalysisEmployeeAttendAbsenceItem", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_AnalysisEmployeeAttendAbsenceItem").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.WorkCalendarId).HasColumnName(@"WorkCalendarId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ShiftConceptDetailId).HasColumnName(@"ShiftConceptDetailId").HasColumnType("int").IsRequired();
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("char(5)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("char(5)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(5);
            builder.Property(x => x.TimeDuration).HasColumnName(@"TimeDuration").HasColumnType("char(6)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(6);
            builder.Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RollCallConceptId).HasColumnName(@"RollCallConceptId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.RollCallDefinitionId).HasColumnName(@"RollCallDefinitionId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.DeleteIsValid).HasColumnName(@"DeleteIsValid").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ModifyIsValid).HasColumnName(@"ModifyIsValid").HasColumnType("bit").IsRequired();
            builder.Property(x => x.GuIdKey).HasColumnName(@"GuIdKey").HasColumnType("varchar(max)").IsRequired(false).IsUnicode(false);
        }
    }

}
// </auto-generated>
