// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace Ksc.HR.Data.Persistant.Configurations
{
    // EmployeeEducationTime
    public class EmployeeEducationTimeConfiguration : IEntityTypeConfiguration<EmployeeEducationTime>
    {
        public void Configure(EntityTypeBuilder<EmployeeEducationTime> builder)
        {
            builder.ToTable("EmployeeEducationTime", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeEducationTime").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TrainingTypeId).HasColumnName(@"TrainingTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.ClassDate).HasColumnName(@"ClassDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            builder.Property(x => x.CreateDateTime).HasColumnName(@"CreateDateTime").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.CreateUser).HasColumnName(@"CreateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.DeletedDate).HasColumnName(@"DeletedDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.DeletedUser).HasColumnName(@"DeletedUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.EmployeeNumber).HasColumnName(@"EmployeeNumber").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.WorkCalendarId).HasColumnName(@"WorkCalendarId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.EmployeeEducationTimes).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeEducationTime_Employee");
            builder.HasOne(a => a.WorkCalendar).WithMany(b => b.EmployeeEducationTimes).HasForeignKey(c => c.WorkCalendarId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeEducationTime_WorkCalendar");

        }
    }

}
// </auto-generated>
