// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // EmployeeTeamWork
    public class EmployeeTeamWorkConfiguration : IEntityTypeConfiguration<EmployeeTeamWork>
    {
        public void Configure(EntityTypeBuilder<EmployeeTeamWork> builder)
        {
            builder.ToTable("EmployeeTeamWork", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeWorkTeam").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TeamWorkId).HasColumnName(@"TeamWorkId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TeamStartDate).HasColumnName(@"TeamStartDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.TeamEndDate).HasColumnName(@"TeamEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.TransferRequestId).HasColumnName(@"TransferRequestId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp(8)").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.EmployeeTeamWorks).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeTeamWork_Employee");
            builder.HasOne(a => a.TeamWork).WithMany(b => b.EmployeeTeamWorks).HasForeignKey(c => c.TeamWorkId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeTeamWork_TeamWork");
            builder.HasOne(a => a.Transfer_Request).WithMany(b => b.EmployeeTeamWorks).HasForeignKey(c => c.TransferRequestId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeTeamWork_Request");
        }
    }

}
// </auto-generated>
