// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // MonthTimeSheetIncluded
    public class MonthTimeSheetIncludedConfiguration : IEntityTypeConfiguration<MonthTimeSheetIncluded>
    {
        public void Configure(EntityTypeBuilder<MonthTimeSheetIncluded> builder)
        {
           // builder.ToTable(tbl => tbl.HasTrigger("[dbo].[ChangeMinuteToTime]([DurationInHour])"));
            builder.ToTable("MonthTimeSheetIncluded", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_MonthTimeSheetIncluded").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.MonthTimeSheetId).HasColumnName(@"MonthTimeSheetId").HasColumnType("int").IsRequired();
            builder.Property(x => x.IncludedDefinitionId).HasColumnName(@"IncludedDefinitionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.DurationInHour).HasColumnName(@"DurationInHour").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.DurationInDay).HasColumnName(@"DurationInDay").HasColumnType("int").IsRequired(false);
            //builder.Property(x => x.DurationInHourFormatted).HasColumnName(@"DurationInHourFormatted").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10).ValueGeneratedOnAddOrUpdate();
            //builder.Property(x => x.DurationInHourFormatted).HasColumnName(@"DurationInHourFormatted").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10)
            //    .HasComputedColumnSql("[dbo].[ChangeMinuteToTime]([DurationInHour])").ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            builder.HasOne(a => a.IncludedDefinition).WithMany(b => b.MonthTimeSheetIncludeds).HasForeignKey(c => c.IncludedDefinitionId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetIncluded_IncludedDefinition");
            builder.HasOne(a => a.MonthTimeSheet).WithMany(b => b.MonthTimeSheetIncludeds).HasForeignKey(c => c.MonthTimeSheetId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetIncluded_MonthTimeSheet");
        }
    }

}
// </auto-generated>
