// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // MonthTimeSheetRollCall
    public class MonthTimeSheetRollCallConfiguration : IEntityTypeConfiguration<MonthTimeSheetRollCall>
    {
        public void Configure(EntityTypeBuilder<MonthTimeSheetRollCall> builder)
        {
            //builder.ToTable(tbl => tbl.HasTrigger("[dbo].[ChangeMinuteToTime]([DurationInMinut])"));
            builder.ToTable("MonthTimeSheetRollCall", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_MonthTimeSheetRollCall").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.MonthTimeSheetId).HasColumnName(@"MonthTimeSheetId").HasColumnType("int").IsRequired();
            builder.Property(x => x.RollCallDefinitionId).HasColumnName(@"RollCallDefinitionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.DurationInMinut).HasColumnName(@"DurationInMinut").HasColumnType("int").IsRequired();
            builder.Property(x => x.DayCountInDailyTimeSheet).HasColumnName(@"DayCountInDailyTimeSheet").HasColumnType("int").IsRequired();
            //builder.Property(x => x.Duration).HasColumnName(@"Duration").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10).ValueGeneratedOnAddOrUpdate();
            //builder.Property(x => x.Duration).HasColumnName(@"Duration").HasColumnType("nvarchar(10)").IsRequired(false).HasMaxLength(10)
            //    .HasComputedColumnSql("[dbo].[ChangeMinuteToTime]([DurationInMinut])").ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IncreasedTimeDuration).HasColumnName(@"IncreasedTimeDuration").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.MonthTimeSheet).WithMany(b => b.MonthTimeSheetRollCalls).HasForeignKey(c => c.MonthTimeSheetId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetRollCall_MonthTimeSheet");
            builder.HasOne(a => a.RollCallDefinition).WithMany(b => b.MonthTimeSheetRollCalls).HasForeignKey(c => c.RollCallDefinitionId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetRollCall_RollCallDefinition");
        }
    }

}
// </auto-generated>
