// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations.Personal
{
    // MonthTimeShitStepper
    public class MonthTimeShitStepperConfiguration : IEntityTypeConfiguration<MonthTimeShitStepper>
    {
        public void Configure(EntityTypeBuilder<MonthTimeShitStepper> builder)
        {
            builder.ToTable("MonthTimeShitStepper", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_MonthTimeShitStepper").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Label).HasColumnName(@"Label").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.OrderNo).HasColumnName(@"OrderNo").HasColumnType("int").IsRequired();
            builder.Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsShowDetails).HasColumnName(@"IsShowDetails").HasColumnType("bit").IsRequired();
            builder.Property(x => x.FunctionDetails).HasColumnName(@"FunctionDetails").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.IsRequiredForMonthSheet).HasColumnName(@"IsRequiredForMonthSheet").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ProcessName).HasColumnName(@"ProcessName").HasColumnType("nvarchar(500)").IsRequired(false);

        }
    }

}
// </auto-generated>
