// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Workshift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.HR.Data.Persistant.Configurations
{
    // MonthTimeSheetDraft
    public class MonthTimeSheetDraftConfiguration : IEntityTypeConfiguration<MonthTimeSheetDraft>
    {
        public void Configure(EntityTypeBuilder<MonthTimeSheetDraft> builder)
        {
            builder.ToTable("MonthTimeSheetDraft", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_MonthTimeSheetDraft").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.YearMonth).HasColumnName(@"YearMonth").HasColumnType("int").IsRequired();
            builder.Property(x => x.WorkTimeId).HasColumnName(@"WorkTimeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ForcedOverTime).HasColumnName(@"ForcedOverTime").HasColumnType("int").IsRequired();
            builder.Property(x => x.DayCount).HasColumnName(@"DayCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ShiftBenefitDayCount).HasColumnName(@"ShiftBenefitDayCount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LastForcedOverTime).HasColumnName(@"LastForcedOverTime").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.MonthTimeSheetDrafts).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetDraft_Employee");
            builder.HasOne(a => a.WorkTime).WithMany(b => b.MonthTimeSheetDrafts).HasForeignKey(c => c.WorkTimeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_MonthTimeSheetDraft_WorkTime");
        }
    }

}
// </auto-generated>
