// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Reward

{
    // RewardBaseSpecific
    /// <summary>
    /// جدول مبنای پاداش ویژه
    /// </summary>
    public class RewardBaseSpecific : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// سال
        /// </summary>
        public int Year { get; set; } // Year

        /// <summary>
        /// ضریب افزایش
        /// </summary>
        public double IncreasedPercent { get; set; } // IncreasedPercent



        /// <summary>
        /// ضریب ظرفیت
        /// </summary>
        public double CapacityPercent { get; set; } // CapacityPercent

        /// <summary>
        /// شروع اعتبار(سال ماه)
        /// </summary>
        public int ValidStartDate { get; set; } // ValidStartDate

        /// <summary>
        /// پایان اعتبار(سال ماه)
        /// </summary>
        public int? ValidEndDate { get; set; } // ValidEndDate

        /// <summary>
        /// توضیحات
        /// </summary>
        public string Description { get; set; } // Description
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string InsertAuthenticateUserName { get; set; } // InsertAuthenticateUserName (length: 50)
        public string UpdateAuthenticateUserName { get; set; } // UpdateAuthenticateUserName (length: 50)

        public bool IsActive { get; set; }
        // Reverse navigation

        /// <summary>
        /// Child Reward_RewardBaseSpecificOfUnitHeaders where [RewardBaseSpecificOfUnitHeader].[RewardBaseSpecificId] point to this entity (FK_RewardBaseSpecificOfUnitHeader_RewardBaseSpecific)
        /// </summary>
        public virtual List<RewardBaseSpecificOfUnitHeader> RewardBaseSpecificOfUnitHeaders { get; set; } // RewardBaseSpecificOfUnitHeader.FK_RewardBaseSpecificOfUnitHeader_RewardBaseSpecific

        public RewardBaseSpecific()
        {
            RewardBaseSpecificOfUnitHeaders = new List<RewardBaseSpecificOfUnitHeader>();
        }
    }

}
// </auto-generated>
