// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Reward
{
    // RewardInSmcDailyProduction
    /// <summary>
    /// برنامه تولید روزانه
    /// </summary>
    public class RewardInSmcDailyProduction : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int RewardInId { get; set; } // RewardInId

        /// <summary>
        /// روز
        /// </summary>
        public int? SmcDay { get; set; } // SmcDay
        
        /// <summary>
        ///مقدار تولید روزانه 
        /// </summary>
        public long? ProductionSmcWeight { get; set; } // ProductionSmcWeight

        /// <summary>
        ///تناژ از دست رفته 
        /// </summary>
        public long? LostSmcWeight { get; set; } // ProductionSmcWeight

        /// <summary>
        ///تناژ از دست رفته محاسباتی 
        /// </summary>
        public long? CalculateLostSmcWeight { get; set; } // CaculateLostSmcWeight

        /// <summary>
        ///  ذوب از دست رفته  محاسباتی
        /// </summary>
        public long? LostHeatWeight { get; set; } // LostHeatWeight


        /// <summary>
        /// تولید برنامه ای
        /// </summary>
        public long? PlanSmcWeight { get; set; } // PlanSmcWeight

        /// <summary>
        /// تعداد ذوب
        /// </summary>
        public int? HeatNumber { get; set; } // HeatNumber

        /// <summary>
        /// تعداد کوره
        /// </summary>
        public int? EafNumber { get; set; } // EafNumber
        public int? Spare2 { get; set; } // Spare2

        /// <summary>
        /// پاداش روزانه اولیه
        /// </summary>
        public long? FirstlyDayReward { get; set; } // FirstlyDayReward

        /// <summary>
        /// پاداش روزانه نهایی
        /// </summary>
        public long? FinalyDayReward { get; set; } // FinalyDayReward


        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)


        // Foreign keys

        /// <summary>
        /// Parent RewardIn pointed by [RewardInSmcDailyProduction].([RewardInId]) (FK_RewardInSmcDailyProduction_RewardIn)
        /// </summary>
        public virtual RewardIn RewardIn { get; set; } // FK_RewardInSmcDailyProduction_RewardIn
        public double? SmcAverage { get; set; }
    }

}
// </auto-generated>
