// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Reward

{
    // RewardBaseHeader
    public class RewardBaseHeader : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// سال
        /// </summary>
        public int Year { get; set; } // Year

        /// <summary>
        /// درصد افزایش
        /// </summary>
        public double IncreasedPercent { get; set; } // IncreasedPercent

        /// <summary>
        /// شروع اعتبار(سال ماه)
        /// </summary>
        public int ValidStartDate { get; set; } // ValidStartDate

        /// <summary>
        /// پایان اعتبار(سال ماه)
        /// </summary>
        public int? ValidEndDate { get; set; } // ValidEndDate

        /// <summary>
        /// توضیحات
        /// </summary>
        public string Description { get; set; } // Description
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string InsertAuthenticateUserName { get; set; } // InsertAuthenticateUserName (length: 50)
        public string UpdateAuthenticateUserName { get; set; } // UpdateAuthenticateUserName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child RewardBaseDetails where [RewardBaseDetail].[RewardBaseHeaderId] point to this entity (FK_RewardBaseDetail_RewardBaseHeader)
        /// </summary>
        public virtual ICollection<RewardBaseDetail> RewardBaseDetails { get; set; } // RewardBaseDetail.FK_RewardBaseDetail_RewardBaseHeader

        public RewardBaseHeader()
        {
            RewardBaseDetails = new List<RewardBaseDetail>();
        }
    }

}
// </auto-generated>
