// <auto-generated>
// ReSharper disable All

using KSC.Domain;

namespace Ksc.HR.Domain.Entities.Chart
{
    // JobPositionHistory
    public class Chart_JobPositionHistory : IEntityBase<long>
    {
        public long Id { get; set; }
        public int StructureId { get; set; }
        public decimal? CostCenter { get; set; }
        /// <summary>
        /// شناشنامه شغلی
        /// </summary>
        public int? JobIdentityId { get; set; } // JobIdentityId
        /// <summary>
        /// وضعیت پست
        /// </summary>
        public int? JobPoisitionStatusId { get; set; } // JobPoisitionStatusId
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? StructureEndDate { get; set; }
        public int? CapacityCount { get; set; }
        public int? WorkingDayCount { get; set; }
        public int? WorkingShiftCount { get; set; }
        public int? WorkingDayOutsourcingCount { get; set; }
        public int? WorkingShiftOutsourcingCount { get; set; }
        public int? PermissionExistCommodityCount { get; set; }
        public int? TemporaryCount { get; set; }
        public int? SubstituteCount { get; set; }
        public int? ExtraCount { get; set; }
        public bool? IsOnCall { get; set; }
        public bool? IsStrategic { get; set; }
        public string InsuranceJobCode { get; set; }
        public double? RewardSpecificEfficincy { get; set; }
        public double? CofficientProximityProduct { get; set; }
        public long? ParentId { get; set; }
        public int? SpecificRewardId { get; set; }
        public string Description { get; set; }
        public int JobPositionId { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public int? JobPositionNatureId { get; set; }
        public DateTime? InsertDate { get; set; }
        public string InsertUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public bool IsActive { get; set; }
        public virtual Chart_JobIdentity JobIdentity { get; set; }
        public virtual Chart_JobPositionStatus JobPositionStatus { get; set; }
        public virtual Chart_RewardSpecific RewardSpecific { get; set; }
        public virtual Chart_JobPosition JobPosition { get; set; }
        public virtual Chart_JobPositionNature JobPositionNature { get; set; }
        public virtual Chart_Structure Chart_Structure { get; set; } // FK_JobPosition_Structure

    }

}
// </auto-generated>
