// <auto-generated>
// ReSharper disable All

using KSC.Domain;

namespace Ksc.HR.Domain.Entities.Chart
{
    // JobPositionIncreasePercent
    public class Chart_JobPositionIncreasePercent : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public double? CoefficientYearsDay { get; set; } // CoefficientYearsDay
        public double? CoefficientYearsShift { get; set; } // CoefficientYearsShift
        public DateTime? StartDate { get; set; } // StartDate
        public DateTime? EndDate { get; set; } // EndDate
        public int JobPositioinId { get; set; } // JobPositioinId

        public DateTime? InsertDate { get; set; } // InsertDate
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsActive { get; set; } // IsActive


        // Foreign keys

        /// <summary>
        /// Parent Chart_JobPosition pointed by [JobPositionIncreasePercent].([JobPositioinId]) (FK_JobPositionIncreasePerson_JobPosition)
        /// </summary>
        public virtual Chart_JobPosition Chart_JobPosition { get; set; } // FK_JobPositionIncreasePerson_JobPosition
    }

}
// </auto-generated>
