// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Chart
{
    // StructureAccess
    public class Chart_StructureAccess : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
    }

}
// </auto-generated>
