// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Rule;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Chart
{
    // JobIdentity
    public class Chart_JobIdentity : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string Code { get; set; } // Code
        public string Title { get; set; } // Title
        public int JobCategoryId { get; set; } // JobCategoryId
        public DateTime? StartDate { get; set; } // StartDate
        public DateTime? EndDate { get; set; } // EndDate

        public DateTime? InsertDate { get; set; } // InsertDate
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child Chart_JobPositions where [JobPosition].[JobIdentityId] point to this entity (FK_JobPosition_JobIdentity)
        /// </summary>
        public virtual ICollection<Chart_JobPosition> Chart_JobPositions { get; set; } // JobPosition.FK_JobPosition_JobIdentity

        /// <summary>
        /// Child Chart_JobPositionHistories where [JobPositionHistory].[JobIdentityId] point to this entity (FK_JobPositionHistory_JobIdentity)
        /// </summary>
        public virtual ICollection<Chart_JobPositionHistory> Chart_JobPositionHistories { get; set; } // JobPositionHistory.FK_JobPositionHistory_JobIdentity
        // Foreign keys

        /// <summary>
        /// Parent Chart_JobCategory pointed by [JobIdentity].([JobCategoryId]) (FK_JobIdentity_JobCategory)
        /// </summary>
        public virtual Chart_JobCategory Chart_JobCategory { get; set; } // FK_JobIdentity_JobCategory

        public Chart_JobIdentity()
        {
            Chart_JobPositions = new List<Chart_JobPosition>();
            Chart_JobPositionHistories = new List<Chart_JobPositionHistory>();
        }
    }

}
// </auto-generated>
