// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Chart

{
    // JobPositionCertificate
    public class Chart_JobPositionCertificate : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int JobCertificateId { get; set; } // JobCertificateId
        public int JobPositionId { get; set; } // JobPositionId
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public bool? IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Chart_JobCertificate pointed by [JobPositionCertificate].([JobCertificateId]) (FK_JobPositionCertificate_JobCertificate1)
        /// </summary>
        public virtual Chart_JobCertificate Chart_JobCertificate { get; set; } // FK_JobPositionCertificate_JobCertificate1

        /// <summary>
        /// Parent Chart_JobPosition pointed by [JobPositionCertificate].([JobPositionId]) (FK_JobPositionCertificate_JobPosition)
        /// </summary>
        public virtual Chart_JobPosition Chart_JobPosition { get; set; } // FK_JobPositionCertificate_JobPosition

    }

}
// </auto-generated>
