// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Emp;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Chart
{
    // StudyField
    public class StudyField : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title

        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public DateTime? UpdateDate { get; set; } // UpdatDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsActive { get; set; } // IsActive

        public string Code { get; set; }
        // Reverse navigation

        /// <summary>
        /// Child Chart_JobPositionFields where [JobPositionField].[StudyFieldId] point to this entity (FK_JobPositionField_StudyField)
        /// </summary>
        public virtual ICollection<Chart_JobPositionField> Chart_JobPositionFields { get; set; } // JobPositionField.FK_JobPositionField_StudyField
        /// <summary>
        /// Child Emp_EmployeeEducationDegrees where [EmployeeEducationDegree].[StudyFieldId] point to this entity (FK_EmployeeEducationDegree_StudyField)
        /// </summary>
        public virtual ICollection<EmployeeEducationDegree> EmployeeEducationDegrees { get; set; } // EmployeeEducationDegree.FK_EmployeeEducationDegree_StudyField

        public StudyField()
        {
            Chart_JobPositionFields = new List<Chart_JobPositionField>();
            EmployeeEducationDegrees = new List<EmployeeEducationDegree>();

        }
    }

}
// </auto-generated>
