// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Pay;
using Ksc.HR.Domain.Entities.Personal;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Emp
{
    // EmployeeBlackList
    public class EmployeeBlackList : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmployeeId { get; set; } // EmployeeId
        public int? OtherPaymentTypeId { get; set; } // OtherPaymentTypeId
        public DateTime StartDate { get; set; } // StartDate
        public DateTime? EndDate { get; set; } // EndDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public DateTime? InsertDate { get; set; } // InsertDate
        public string RemoteIpAddress { get; set; } // RemoteIpAddress (length: 50)
        public string AuthenticateUserName { get; set; } // AuthenticateUserName (length: 50)
        public bool IsActive { get; set; }


        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [EmployeeBlackList].([EmployeeId]) (FK_EmployeeBlackList_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeBlackList_Employee
        public virtual OtherPaymentType  OtherPaymentType { get; set; } // FK_EmployeeBlackList_OtherPaymentType
    }

}
// </auto-generated>
