// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Rule;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Emp
{
    // EmployeeHistoryTypeEmployement
    /// <summary>
    /// سوابق استخدامی فرد
    /// </summary>
    public class EmployeeHistoryTypeEmployement : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int? EmployeeId { get; set; } // EmployeeId
        public int? HistoryTypeEmployementId { get; set; } // HistoryTypeEmployementId
        public int? Duration { get; set; } // Duration

        /// <summary>
        /// تاریخ درج
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر درج کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [EmployeeHistoryTypeEmployement].([EmployeeId]) (FK_EmployeeHistoryTypeEmployement_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeHistoryTypeEmployement_Employee

        /// <summary>
        /// Parent HistoryTypeEmployement pointed by [EmployeeHistoryTypeEmployement].([HistoryTypeEmployementId]) (FK_EmployeeHistoryTypeEmployement_HistoryTypeEmployement)
        /// </summary>
        public virtual HistoryTypeEmployement HistoryTypeEmployement { get; set; } // FK_EmployeeHistoryTypeEmployement_HistoryTypeEmployement
    }

}
// </auto-generated>
