// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Chart;
using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Workshift;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay
{
    // BudgetRewardEmployee
    public class BudgetRewardEmployee : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// شناسه‌ی جدول جزئیات بودجه
        /// </summary>
        public int BudgetRewardDetailId { get; set; } // BudgetRewardDetailId

        /// <summary>
        /// شناسه پرسنل
        /// </summary>
        public int EmployeeId { get; set; } // EmployeeId

        /// <summary>
        /// مبلغ پاداش
        /// </summary>
        public long RewardAmount { get; set; } // RewardAmount

        /// <summary>
        /// شناسه تیم کاری جاری فرد
        /// </summary>
        public int TeamWorkId { get; set; } // TeamWorkId

        /// <summary>
        /// ماه
        /// </summary>
        public int YearMonth { get; set; } // YearMonth

        /// <summary>
        /// شناسه وضعیت بودجه
        /// </summary>
        public int BudgetRewardStatusId { get; set; } // BudgetRewardStatusId

        /// <summary>
        /// کد شغل جاری فرد
        /// </summary>
        public int JobPositionId { get; set; } // JobPositionId

        /// <summary>
        /// آیا فعال است؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        /// <summary>
        /// آیا تکی افزوده شده؟
        /// </summary>
        public bool IsExtra { get; set; } // IsActive

        /// <summary>
        /// تاریخ ثبت
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// نام کاربری ثبت کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ بروزرسانی
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// نام کاربری بروزرسانی کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// دامنه شرکت
        /// </summary>
        public string DomainName { get; set; } // DomainName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Pay_BudgetRewardEmployeeHistories where [BudgetRewardEmployeeHistory].[BudgetRewardEmployeeId] point to this entity (FK_BudgetRewardEmployeeHistory_BudgetRewardEmployee)
        /// </summary>
        public virtual ICollection<BudgetRewardEmployeeHistory> BudgetRewardEmployeeHistories { get; set; } // BudgetRewardEmployeeHistory.FK_BudgetRewardEmployeeHistory_BudgetRewardEmployee

        // Foreign keys

        /// <summary>
        /// Parent Chart_JobPosition pointed by [BudgetRewardEmployee].([JobPositionId]) (FK_BudgetRewardEmployee_JobPosition)
        /// </summary>
        public virtual Chart_JobPosition Chart_JobPosition { get; set; } // FK_BudgetRewardEmployee_JobPosition

        /// <summary>
        /// Parent Employee pointed by [BudgetRewardEmployee].([EmployeeId]) (FK_BudgetRewardEmployee_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_BudgetRewardEmployee_Employee

        /// <summary>
        /// Parent Pay_BudgetRewardDetail pointed by [BudgetRewardEmployee].([BudgetRewardDetailId]) (FK_BudgetRewardEmployee_BudgetRewardDetail)
        /// </summary>
        public virtual BudgetRewardDetail BudgetRewardDetail { get; set; } // FK_BudgetRewardEmployee_BudgetRewardDetail

        /// <summary>
        /// Parent Pay_BudgetRewardStatu pointed by [BudgetRewardEmployee].([BudgetRewardStatusId]) (FK_BudgetRewardEmployee_BudgetRewardStatus)
        /// </summary>
        public virtual BudgetRewardStatus BudgetRewardStatus { get; set; } // FK_BudgetRewardEmployee_BudgetRewardStatus

        /// <summary>
        /// Parent TeamWork pointed by [BudgetRewardEmployee].([TeamWorkId]) (FK_BudgetRewardEmployee_TeamWork)
        /// </summary>
        public virtual TeamWork TeamWork { get; set; } // FK_BudgetRewardEmployee_TeamWork

        public BudgetRewardEmployee()
        {
            BudgetRewardEmployeeHistories = new List<BudgetRewardEmployeeHistory>();
        }
    }

}
// </auto-generated>
