// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // EmployeeDeductionHeader
    /// <summary>
    /// بدهی پرسنل
    /// </summary>
    public class EmployeeDeductionHeader : IEntityBase<long>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public long Id { get; set; } // Id (Primary key)


        /// <summary>
        /// سال ماه
        /// </summary>
        public int YearMonth { get; set; } // YearMonth
        /// <summary>
        /// شناسه پرسنلی
        /// </summary>
        public int EmployeeId { get; set; } // EmployeeId
        public int? AccountCodeId { get; set; } // AccountCodeId
        public string BankLoanNumber { get; set; } // BankLoanNumber

        /// <summary>
        /// شناسه نوع بدهی
        /// </summary>
        public int EmployeeDeductionTypeId { get; set; } // EmployeeDeductionTypeId

        /// <summary>
        /// توضیحات
        /// </summary>
        public string Description { get; set; } // Description

        /// <summary>
        /// مبلغ کل بدهی/مانده بدهی
        /// </summary>
        public long? TotalDeductionAmount { get; set; } // TotalDeductionAmount

        /// <summary>
        /// مبلغ کل پس انداز
        /// </summary>
        public long? TotalSaveAmount { get; set; } // TotalSaveAmount

        /// <summary>
        /// مبلغ وام
        /// </summary>
        public long? LoanAmount { get; set; } // LoanAmount

        /// <summary>
        /// مبلغ وام پرداختی
        /// </summary>
        public long? PayableLoanAmount { get; set; } // PayableLoanAmount

        /// <summary>
        /// تعداد اقساط
        /// </summary>
        public int? InstallmentCount { get; set; } // InstallmentCount

        /// <summary>
        /// کاربر ثبت کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ثبت
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive
        public string DomainName { get; set; } // DomainName (length: 50)
        public DateTime? EndDate { get; set; } // EndDate

        // Reverse navigation

        /// <summary>
        /// Child EmployeeDeductionDetails where [EmployeeDeductionDetail].[EmployeeDeductionHeaderId] point to this entity (FK_EmployeeDeductionDetail_EmployeeDeductionHeader)
        /// </summary>
        public virtual ICollection<EmployeeDeductionDetail> EmployeeDeductionDetails { get; set; } // EmployeeDeductionDetail.FK_EmployeeDeductionDetail_EmployeeDeductionHeader

        /// <summary>
        /// Child EmployeeDeductionInstallmentPutOffs where [EmployeeDeductionInstallmentPutOff].[EmployeeDeductionHeaderId] point to this entity (FK_EmployeeDeductionInstallmentDeferrals_EmployeeDeductionHeader)
        /// </summary>
        public virtual ICollection<EmployeeDeductionInstallmentPutOff> EmployeeDeductionInstallmentPutOffs { get; set; } // EmployeeDeductionInstallmentPutOff.FK_EmployeeDeductionInstallmentDeferrals_EmployeeDeductionHeader

        // Foreign keys

        /// <summary>
        /// Parent AccountCode pointed by [EmployeeDeductionHeader].([AccountCodeId]) (FK_EmployeeDeductionHeader_AccountCode)
        /// </summary>
        public virtual AccountCode AccountCode { get; set; } // FK_EmployeeDeductionHeader_AccountCode


        /// <summary>
        /// Parent Employee pointed by [EmployeeDeductionHeader].([EmployeeId]) (FK_EmployeeDeductionHeader_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_EmployeeDeductionHeader_Employee

        /// <summary>
        /// Parent EmployeeDeductionType pointed by [EmployeeDeductionHeader].([EmployeeDeductionTypeId]) (FK_EmployeeDeductionHeader_EmployeeDeductionType)
        /// </summary>
        public virtual EmployeeDeductionType EmployeeDeductionType { get; set; } // FK_EmployeeDeductionHeader_EmployeeDeductionType





        public EmployeeDeductionHeader()
        {
            EmployeeDeductionDetails = new List<EmployeeDeductionDetail>();
            EmployeeDeductionInstallmentPutOffs = new List<EmployeeDeductionInstallmentPutOff>();
        }
    }

}
// </auto-generated>
