// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // EmployeeLoanDeductionHeader
    /// <summary>
    /// اطلاعات وام پس انداز پرسنل
    /// </summary>
    public class EmployeeLoanDeductionHeader : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// تاریخ شروع
        /// </summary>
        public DateTime StartDate { get; set; } // StartDate

        /// <summary>
        /// تاریخ پایان
        /// </summary>
        public DateTime? EndDate { get; set; } // EndDate

        /// <summary>
        /// ضریب افزایشی وام
        /// </summary>
        public double IncreasePercent { get; set; } // IncreasePercent

        /// <summary>
        /// کد حساب پرداختی وام
        /// </summary>
        public int PaymentAccountCodeId { get; set; } // PaymentAccountCodeId

        /// <summary>
        /// کد حساب پرداخت اقساط
        /// </summary>
        public int InstallmentAccountCodeId { get; set; } // InstallmentAccountCodeId

        /// <summary>
        /// تعداد اقساط
        /// </summary>
        public int InstallmentNumber { get; set; } // InstallmentNumber

        /// <summary>
        /// تعداد اقساط وام اولی
        /// </summary>
        public int? FirstTimeInstallmentNumber { get; set; } // FirstTimeInstallmentNumber

        /// <summary>
        /// مبلغ وام اولی
        /// </summary>
        public long? FirstTimeLoanAmount { get; set; } // FirstTimeLoanAmount

        /// <summary>
        /// درصد وام اولی
        /// </summary>
        public double? FirstTimePercent { get; set; } // FirstTimePercent

        /// <summary>
        /// تعداد اقساط مبنای پرداخت وام بعدی
        /// </summary>
        public int? NextInstallmentNumber { get; set; } // NextInstallmentNumber
        /// <summary>
        /// تعداد اقساط مبنای پرداخت وام  خارج از نوبت 
        /// </summary>
        public int? OutOfTurnInstallmentNumber { get; set; } // OutOfTurnInstallmentNumber

        /// <summary>
        /// حداقل روز حصور جهت اخذ وام
        /// </summary>
        public int? MinWorkDay { get; set; } // MinWorkDay

        /// <summary>
        /// کاربر ثبت کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ثبت
        /// </summary>
        public DateTime InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool IsActive { get; set; } // IsActive

        /// <summary>
        /// دامنه شرکت
        /// </summary>
        public string DomainName { get; set; } // DomainName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child EmployeeLoanDeductionDetails where [EmployeeLoanDeductionDetail].[EmployeeLoanDeductionHeaderId] point to this entity (FK_EmployeeLoanDeductionDetail_EmployeeLoanDeductionHeader)
        /// </summary>
        public virtual ICollection<EmployeeLoanDeductionDetail> EmployeeLoanDeductionDetails { get; set; } // EmployeeLoanDeductionDetail.FK_EmployeeLoanDeductionDetail_EmployeeLoanDeductionHeader

        // Foreign keys

        /// <summary>
        /// Parent AccountCode pointed by [EmployeeLoanDeductionHeader].([InstallmentAccountCodeId]) (FK_EmployeeLoanDeductionHeader_AccountCode1)
        /// </summary>
        public virtual AccountCode InstallmentAccountCode { get; set; } // FK_EmployeeLoanDeductionHeader_AccountCode1

        /// <summary>
        /// Parent AccountCode pointed by [EmployeeLoanDeductionHeader].([PaymentAccountCodeId]) (FK_EmployeeLoanDeductionHeader_AccountCode)
        /// </summary>
        public virtual AccountCode PaymentAccountCode { get; set; } // FK_EmployeeLoanDeductionHeader_AccountCode

        public EmployeeLoanDeductionHeader()
        {
            EmployeeLoanDeductionDetails = new List<EmployeeLoanDeductionDetail>();
        }
    }

}
// </auto-generated>
