// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Salary;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // EmployeeDeductionType
    /// <summary>
    /// انواع بدهی
    /// </summary>
    public class EmployeeDeductionType : IEntityBase<int>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// عنوان
        /// </summary>
        public string Title { get; set; } // Title

        /// <summary>
        /// در پرتال نمایش داده شود؟
        /// </summary>
        public bool IsShowPortal { get; set; } // IsShowPortal


        /// <summary>
        /// نیازمند تایید حقوق دستمزد؟
        /// </summary>
        public bool NeedConfirm { get; set; } // IsShowPortal

        /// <summary>
        /// کاربر ثبت کننده
        /// </summary>
        public string InsertUser { get; set; } // InsertUser (length: 50)

        /// <summary>
        /// تاریخ ثبت
        /// </summary>
        public DateTime? InsertDate { get; set; } // InsertDate

        /// <summary>
        /// کاربر ویرایش کننده
        /// </summary>
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        /// <summary>
        /// تاریخ ویرایش
        /// </summary>
        public DateTime? UpdateDate { get; set; } // UpdateDate

        /// <summary>
        /// فعال؟
        /// </summary>
        public bool? IsActive { get; set; } // IsActive
        public string DomainName { get; set; } // DomainName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child EmployeeDeductionHeaders where [EmployeeDeductionHeader].[EmployeeDeductionTypeId] point to this entity (FK_EmployeeDeductionHeader_EmployeeDeductionType)
        /// </summary>
        public virtual ICollection<EmployeeDeductionHeader> EmployeeDeductionHeaders { get; set; } // EmployeeDeductionHeader.FK_EmployeeDeductionHeader_EmployeeDeductionType

        /// <summary>
        /// Child EmployeeDeductionTemps where [EmployeeDeductionTemp].[EmployeeDeductionTypeId] point to this entity (FK_EmployeeDeductionTemp_EmployeeDeductionType)
        /// </summary>
        public virtual ICollection<EmployeeDeductionTemp> EmployeeDeductionTemps { get; set; } // EmployeeDeductionTemp.FK_EmployeeDeductionTemp_EmployeeDeductionType

        /// <summary>
        /// Child AccountCodeDeductionTypes where [AccountCodeDeductionType].[EmployeeDeductionTypeId] point to this entity (FK_AccountCodeDeductionType_EmployeeDeductionType)
        /// </summary>
        public virtual ICollection<AccountCodeDeductionType> AccountCodeDeductionTypes { get; set; } // AccountCodeDeductionType.FK_AccountCodeDeductionType_EmployeeDeductionType

        public EmployeeDeductionType()
        {
            AccountCodeDeductionTypes = new List<AccountCodeDeductionType>();
            EmployeeDeductionHeaders = new List<EmployeeDeductionHeader>();
            EmployeeDeductionTemps = new List<EmployeeDeductionTemp>();
        }
    }

}
// </auto-generated>
