// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay
{
    // EmployeeOtherPaymentTemplate
    public class EmployeeOtherPaymentTemplate : IEntityBase<long>
    {
        public long Id { get; set; } // Id (Primary key)
        public Guid? FileGuid { get; set; } // FileGuid
        public string EmployeeFamily { get; set; } // EmployeeFamily
        public string EmployeeNumber { get; set; } // EmployeeNumber (length: 50)
        public long? Amount { get; set; } // Amount
        public int EmployeeId { get; set; }
        public string CostCenterCode { get; set; }
    }

}
// </auto-generated>
