// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // EmployeeDeductionStatus
    public class EmployeeDeductionStatus
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child EmployeeDeductionDetails where [EmployeeDeductionDetail].[EmployeeDeductionStatusId] point to this entity (FK_EmployeeDeductionDetail_EmployeeDeductionStatus)
        /// </summary>
        public virtual ICollection<EmployeeDeductionDetail> EmployeeDeductionDetails { get; set; } // EmployeeDeductionDetail.FK_EmployeeDeductionDetail_EmployeeDeductionStatus

        public EmployeeDeductionStatus()
        {
            EmployeeDeductionDetails = new List<EmployeeDeductionDetail>();
        }
    }

}
// </auto-generated>
