// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
namespace Ksc.HR.Domain.Entities.Pay

{
    // EmployeeDeductionDetail
    /// <summary>
    /// جزئیات  بدهی پرسنل
    /// </summary>
    public class EmployeeDeductionDetail : IEntityBase<long>
    {
        /// <summary>
        /// شناسه
        /// </summary>
        public long Id { get; set; } // Id (Primary key)

        /// <summary>
        /// شناسه بدهی پرسنل
        /// </summary>
        public long EmployeeDeductionHeaderId { get; set; } // EmployeeDeductionHeaderId


        /// <summary>
        /// تاریخ قسط
        /// </summary>
        public int InstallmentDate { get; set; } // InstallmentDate

        /// <summary>
        /// مبلغ قسط
        /// </summary>
        public long InstallmentAmount { get; set; } // InstallmentAmount

        /// <summary>
        /// وضعیت پرداخت قسط
        /// </summary>
        public int EmployeeDeductionStatusId { get; set; } // EmployeeDeductionStatusId

        /// <summary>
        /// تاریخ پرداخت قسط
        /// </summary>
        public int? InstallmentPaymentDate { get; set; } // InstallmentPaymentDate

        public DateTime? SendMISDate { get; set; }

        public string SendMISUser { get; set; }

        // Foreign keys

        /// <summary>
        /// Parent EmployeeDeductionHeader pointed by [EmployeeDeductionDetail].([EmployeeDeductionHeaderId]) (FK_EmployeeDeductionDetail_EmployeeDeductionHeader)
        /// </summary>
        public virtual EmployeeDeductionHeader EmployeeDeductionHeader { get; set; } // FK_EmployeeDeductionDetail_EmployeeDeductionHeader

        /// <summary>
        /// Parent EmployeeDeductionStatu pointed by [EmployeeDeductionDetail].([EmployeeDeductionStatusId]) (FK_EmployeeDeductionDetail_EmployeeDeductionStatus)
        /// </summary>
        public virtual EmployeeDeductionStatus EmployeeDeductionStatus { get; set; } // FK_EmployeeDeductionDetail_EmployeeDeductionStatus
    }

}
// </auto-generated>
