// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay
{
    // OtherPaymentHeaderType
    public class OtherPaymentHeaderType : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int OtherPaymentHeaderId { get; set; } // OtherPaymentHeaderId
        public int OtherPaymentTypeId { get; set; } // OtherPaymentTypeId

        // Foreign keys

        /// <summary>
        /// Parent Pay_OtherPaymentHeader pointed by [OtherPaymentHeaderType].([OtherPaymentHeaderId]) (FK_OtherPaymentHeaderType_OtherPaymentHeader)
        /// </summary>
        public virtual OtherPaymentHeader OtherPaymentHeader { get; set; } // FK_OtherPaymentHeaderType_OtherPaymentHeader

        /// <summary>
        /// Parent Pay_OtherPaymentType pointed by [OtherPaymentHeaderType].([OtherPaymentTypeId]) (FK_OtherPaymentHeaderType_OtherPaymentType)
        /// </summary>
        public virtual OtherPaymentType OtherPaymentType { get; set; } // FK_OtherPaymentHeaderType_OtherPaymentType
       

    }

}
// </auto-generated>
