// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // PaymentAdditionalSetting
    public class PaymentAdditionalSetting : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// تاریخ شروع(سال-ماه)
        /// </summary>
        public int YearMonthStart { get; set; } // YearMonthStart

        /// <summary>
        /// تاریخ پایان(سال-ماه)
        /// </summary>
        public int? YearMonthEnd { get; set; } // YearMonthEnd

        /// <summary>
        /// کد حساب
        /// </summary>
        public int AccountCodeId { get; set; } // AccountCodeId

        /// <summary>
        /// مبلغ پایه
        /// </summary>
        public long? BaseAmount { get; set; } // BaseAmount
        public bool AllWorkCity { get; set; } // AllWorkCity
        public bool AllJobCategory { get; set; } // AllJobCategory
        public bool IsActive { get; set; } // IsActive
        public DateTime? InsertDate { get; set; } // InsertDate
        public DateTime? UpdateDate { get; set; } // UpdateDate
        public string InsertUser { get; set; } // InsertUser (length: 50)
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Pay_PaymentAdditionalSettingJobCategories where [PaymentAdditionalSettingJobCategory].[PaymentAdditionalSettingId] point to this entity (FK_PaymentAdditionalSettingJobCategory_PaymentAdditionalSetting)
        /// </summary>
        public virtual ICollection<PaymentAdditionalSettingJobCategory> PaymentAdditionalSettingJobCategories { get; set; } // PaymentAdditionalSettingJobCategory.FK_PaymentAdditionalSettingJobCategory_PaymentAdditionalSetting

        /// <summary>
        /// Child Pay_PaymentAdditionalSettingWorkCities where [PaymentAdditionalSettingWorkCity].[PaymentAdditionalSettingId] point to this entity (FK_PaymentAdditionalSettingWorkCity_PaymentAdditionalSetting)
        /// </summary>
        public virtual ICollection<PaymentAdditionalSettingWorkCity> PaymentAdditionalSettingWorkCities { get; set; } // PaymentAdditionalSettingWorkCity.FK_PaymentAdditionalSettingWorkCity_PaymentAdditionalSetting
        public virtual ICollection<PaymentAdditionalSettingJobPosition> PaymentAdditionalSettingJobPositions { get; set; } // PaymentAdditionalSettingWorkCity.FK_PaymentAdditionalSettingWorkCity_PaymentAdditionalSetting
        
        public PaymentAdditionalSetting()
        {
            PaymentAdditionalSettingJobCategories = new List<PaymentAdditionalSettingJobCategory>();
            PaymentAdditionalSettingWorkCities = new List<PaymentAdditionalSettingWorkCity>();
        }
    }

}
// </auto-generated>
