// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Chart;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay
{
    // PaymentAdditionalSettingJobCategory
    public class PaymentAdditionalSettingJobCategory : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int PaymentAdditionalSettingId { get; set; } // PaymentAdditionalSettingId
        public int JobCategoryId { get; set; } // JobCategoryId
        public int? JobPositionStatusId { get; set; } // JobPositionStatusId

        // Foreign keys

        /// <summary>
        /// Parent Chart_JobCategory pointed by [PaymentAdditionalSettingJobCategory].([JobCategoryId]) (FK_PaymentAdditionalSettingJobCategory_JobCategory)
        /// </summary>
        public virtual Chart_JobCategory Chart_JobCategory { get; set; } // FK_PaymentAdditionalSettingJobCategory_JobCategory
        public virtual Chart_JobPositionStatus Chart_JobPositionStatus { get; set; } // FK_PaymentAdditionalSettingJobCategory_Chart_JobPositionStatus

        /// <summary>
        /// Parent Pay_PaymentAdditionalSetting pointed by [PaymentAdditionalSettingJobCategory].([PaymentAdditionalSettingId]) (FK_PaymentAdditionalSettingJobCategory_PaymentAdditionalSetting)
        /// </summary>
        public virtual PaymentAdditionalSetting PaymentAdditionalSetting { get; set; } // FK_PaymentAdditionalSettingJobCategory_PaymentAdditionalSetting


    }

}
// </auto-generated>
