// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Personal;
using KSC.Domain;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Pay

{
    // PaymentAdditionalDetail
    public class PaymentAdditionalDetail : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int PaymentAdditionalHeaderId { get; set; } // PaymentAdditionalHeaderId
        public int EmployeeId { get; set; } // EmployeeId

        /// <summary>
        /// مبلغ پایه پرداخت
        /// </summary>
        public long? BasePaymentAmount { get; set; } // BasePaymentAmount

        /// <summary>
        /// مبلغ  پرداخت شده
        /// </summary>
        public long? PaymentAmount { get; set; } // PaymentAmount

        /// <summary>
        /// پرداخت به تعداد روز
        /// </summary>
        public int? PayAsDay { get; set; } // PayAsDay

        /// <summary>
        /// پرداخت به تعداد نفرات
        /// </summary>
        public int? PayAsPersonCount { get; set; } // PayAsPersonCount

        /// <summary>
        /// پرداخت به مدت به دقیقه
        /// </summary>
        public int? PayAsMinuteDuration { get; set; } // PayAsMinuteDuration

        /// <summary>
        /// لسیت سیاه است؟
        /// </summary>
        public bool IsBlackList { get; set; } // IsBlackList

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [PaymentAdditionalDetail].([EmployeeId]) (FK_PaymentAdditionalDetail_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_PaymentAdditionalDetail_Employee

        /// <summary>
        /// Parent Pay_PaymentAdditionalHeader pointed by [PaymentAdditionalDetail].([PaymentAdditionalHeaderId]) (FK_PaymentAdditionalDetail_PaymentAdditionalHeader)
        /// </summary>
        public virtual PaymentAdditionalHeader PaymentAdditionalHeader { get; set; } // FK_PaymentAdditionalDetail_PaymentAdditionalHeader
    }

}
// </auto-generated>
