// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Pay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Ksc.Hr.Data.Persistant.Configurations.Pay

{
    // EmployeeDeductionStatus
    public class EmployeeDeductionStatusConfiguration : IEntityTypeConfiguration<EmployeeDeductionStatus>
    {
        public void Configure(EntityTypeBuilder<EmployeeDeductionStatus> builder)
        {
            builder.ToTable("EmployeeDeductionStatus", "Pay");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeDeductionStatus").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
