// <auto-generated>
// ReSharper disable All

using Ksc.HR.Domain.Entities.Pay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ksc.Hr.Data.Persistant.Configurations
{
    // EmployeeDeductionAdditional
    public class EmployeeDeductionAdditionalConfiguration : IEntityTypeConfiguration<EmployeeDeductionAdditional>
    {
        public void Configure(EntityTypeBuilder<EmployeeDeductionAdditional> builder)
        {
            builder.ToTable("EmployeeDeductionAdditional", "Pay");
            builder.HasKey(x => x.Id).HasName("PK_EmployeeDeductionAdditional").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.DeductionAdditionalId).HasColumnName(@"DeductionAdditionalId").HasColumnType("int").IsRequired();
            builder.Property(x => x.YearMonthStart).HasColumnName(@"YearMonthStart").HasColumnType("int").IsRequired();
            builder.Property(x => x.YearMonthEnd).HasColumnName(@"YearMonthEnd").HasColumnType("int").IsRequired();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.InsertUser).HasColumnName(@"InsertUser").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.InsertDate).HasColumnName(@"InsertDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdateUser).HasColumnName(@"UpdateUser").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.RemoteIpAddress).HasColumnName(@"RemoteIpAddress").HasColumnType("varchar(50)").IsRequired(false).IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.AuthenticateUserName).HasColumnName(@"AuthenticateUserName").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);

            // Foreign keys
            //builder.HasOne(a => a.Employee).WithMany(b => b.EmployeeDeductionAdditionals).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeDeductionAdditional_Employee");
            builder.HasOne(a => a.Pay_DeductionAdditional).WithMany(b => b.EmployeeDeductionAdditionals).HasForeignKey(c => c.DeductionAdditionalId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_EmployeeDeductionAdditional_DeductionAdditional");
        }
    }

}
// </auto-generated>
