// <auto-generated>
// ReSharper disable All

using KSC.Domain;
using Ksc.HR.Domain.Entities.General;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Ksc.HR.Domain.Entities.Transfer
{
    // RequestType
    public class Transfer_RequestType : BaseModel, IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)

        /// <summary>
        /// نوع درحواست جا به جایی
        /// </summary>
        public string Title { get; set; } // Title (length: 500)

        // Reverse navigation

        /// <summary>
        /// Child Transfer_RequestReasonTypes where [RequestReasonType].[TransferRequestTypeId] point to this entity (FK_RequestReasonType_RequestType)
        /// </summary>
        public virtual ICollection<Transfer_RequestReasonType> Transfer_RequestReasonTypes { get; set; } // RequestReasonType.FK_RequestReasonType_RequestType

        public Transfer_RequestType()
        {
            Transfer_RequestReasonTypes = new List<Transfer_RequestReasonType>();
        }
    }

}
// </auto-generated>
