// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

using KSC.Domain;
using Ksc.HR.Domain.Entities.Workshift;

namespace Ksc.HR.Domain.Entities.Oncall
{
    // WorkTime
    public class OnCall_WorkTime : IEntityBase<int>
    {
        public int Id { get; set; } // Id (Primary key)
        public int OnCallTypeId { get; set; } // OnCallTypeId
        public int WorkTimeId { get; set; } // WorkTimeId

        // Foreign keys

        /// <summary>
        /// Parent OnCall_Type pointed by [WorkTime].([OnCallTypeId]) (FK_OnCallWorkTime_OnCallType)
        /// </summary>
        public virtual OnCall_Type OnCall_Type { get; set; } // FK_OnCallWorkTime_OnCallType

        /// <summary>
        /// Parent WorkTime pointed by [WorkTime].([WorkTimeId]) (FK_OnCallWorkTime_WorkTime)
        /// </summary>
        public virtual WorkTime WorkTime { get; set; } // FK_OnCallWorkTime_WorkTime
    }

}
// </auto-generated>
